import { mkdir, rm, writeFile, copyFile, readFile } from 'node:fs/promises';
import { dirname, resolve, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { site, services, regions, brands, guides, linkedRegionSlugs, brandRegionPairs, knownUrls } from './data.mjs';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const out = join(root, 'dist');
const base = (process.env.SITE_URL || site.siteUrl).replace(/\/$/, '');
const esc = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const absolute = path => `${base}${path}`;
const phoneLink = `tel:+${site.phoneDigits}`;
const whatsapp = `https://wa.me/${site.phoneDigits}`;
const logo = '/assets/images/dost-teknik-logo.webp';
const photoOutside = '/assets/images/dost-teknik-isletme-dis.webp';
const photoInside = '/assets/images/dost-teknik-isletme-ici.webp';
const icons = {
  phone:'<path d="M22 16.9v3a2 2 0 0 1-2.2 2A19.8 19.8 0 0 1 11.2 19a19.4 19.4 0 0 1-6-6A19.8 19.8 0 0 1 2.1 4.2 2 2 0 0 1 4.1 2h3a2 2 0 0 1 2 1.7l.5 2.7a2 2 0 0 1-.6 1.8L7.5 9.7a16 16 0 0 0 6 6l1.5-1.5a2 2 0 0 1 1.8-.6l2.7.5a2 2 0 0 1 1.7 2.8Z"/>',
  chat:'<path d="M21 11.5a8.4 8.4 0 0 1-12.4 7.4L3 20l1.2-5.3A8.5 8.5 0 1 1 21 11.5Z"/><path d="M8 9.5c.7 2.2 2.3 3.8 4.5 4.5"/>',
  snow:'<path d="M12 2v20M4 7l16 10M20 7 4 17M8.5 4.5 12 2l3.5 2.5M8.5 19.5 12 22l3.5-2.5M3.5 10 4 7l3.5-.5M16.5 17.5 20 17l.5-3M20 7l.5 3-3.5.5M4 17l-.5-3 3.5-.5"/>',
  appliance:'<rect x="4" y="2.5" width="16" height="19" rx="2"/><path d="M4 8h16M8 5.3h.01M11 5.3h.01M8 11v7M12 11v7M16 11v7"/>',
  pin:'<path d="M20 10c0 5-8 12-8 12S4 15 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/>',
  clock:'<circle cx="12" cy="12" r="9.5"/><path d="M12 6.5V12l4 2"/>',
  arrow:'<path d="M5 12h14M13 6l6 6-6 6"/>',
  menu:'<path d="M4 6h16M4 12h16M4 18h16"/>',
  wrench:'<path d="M14.7 6.3a5 5 0 0 0-6.6 6.6L2.5 18.5a2.1 2.1 0 0 0 3 3l5.6-5.6a5 5 0 0 0 6.6-6.6L14.5 12 12 9.5l2.7-3.2Z"/>',
  chevron:'<path d="m6 9 6 6 6-6"/>'
};
const icon = (name, cls='') => `<svg class="icon${cls?` ${cls}`:''}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[name]||icons.arrow}</svg>`;
const faq = (q,a) => `<details class="faq"><summary>${esc(q)}${icon('chevron')}</summary><p>${esc(a)}</p></details>`;
const faqSchema = items => ({'@context':'https://schema.org','@type':'FAQPage',mainEntity:items.map(([q,a])=>({'@type':'Question',name:q,acceptedAnswer:{'@type':'Answer',text:a}}))});
const link = (href,label,cls='') => `<a${cls?` class="${cls}"`:''} href="${esc(href)}">${esc(label)}</a>`;
const cards = (items, label=x=>x.name) => `<div class="cards">${items.map(x=>`<a class="card" href="${esc(x.url)}"><span>${esc(label(x))}</span>${icon('arrow','card-arrow')}</a>`).join('')}</div>`;
const serviceCards = items => `<div class="service-grid">${items.map((item,i)=>`<a class="service-card" href="${item.url}"><span class="service-icon">${icon(i%3===1?'wrench':i%3===2?'appliance':'snow')}</span><span class="service-card-copy"><strong>${esc(item.name)}</strong><small>${esc(item.description)}</small><span class="text-link">Hizmeti incele ${icon('arrow')}</span></span></a>`).join('')}</div>`;
const crumbSchema = crumbs => ({'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:crumbs.map((c,i)=>({'@type':'ListItem',position:i+1,name:c.name,item:absolute(c.url)}))});
const businessSchema = {
  '@context':'https://schema.org','@type':'HVACBusiness','name':site.name,'url':base,'image':[absolute(photoOutside),absolute(photoInside)],'logo':absolute(logo),
  'telephone':site.phone,'address':{'@type':'PostalAddress','streetAddress':'Akçaalan Mahallesi Zübeyde Hanım Caddesi No:30/2','addressLocality':'Bodrum','addressRegion':'Muğla','addressCountry':'TR'},
  'areaServed':regions.map(r=>({'@type':'Place','name':r.name}))
};
const navLinks = `<a href="/hizmetler/">Hizmetler</a><a href="/bolgeler/">Bölgeler</a><a href="/markalar/">Markalar</a><a href="/bilgi-merkezi/">Bilgi Merkezi</a><a href="/hakkimizda.html">Hakkımızda</a><a href="/iletisim.html">İletişim</a>`;
const siteHeader = `<a class="skip" href="#main">İçeriğe geç</a><div class="topbar"><div class="wrap top-inner"><span>Turgutreis merkezli · Bodrum Yarımadası genelinde servis</span><span class="top-contact">${icon('clock')} ${site.hours}<a href="${phoneLink}">${icon('phone')} ${site.phone}</a></span></div></div><header class="header"><div class="wrap nav"><a class="brand" href="/" aria-label="Dost Teknik ana sayfa"><img src="${logo}" width="408" height="164" alt="Dost Teknik Klima ve Beyaz Eşya Servisi"></a><button class="nav-toggle" aria-expanded="false" aria-controls="primary-nav" aria-label="Menüyü aç">${icon('menu','menu-glyph')}<span>Menü</span></button><nav id="primary-nav" aria-label="Ana menü"><div class="drawer-heading"><span>Menü</span><button class="menu-close" type="button" aria-label="Menüyü kapat">×</button></div>${navLinks}<div class="drawer-actions"><a class="button" href="${phoneLink}">${icon('phone')} Hemen ara</a><a class="button button-whatsapp" href="${whatsapp}" rel="noopener">${icon('chat')} WhatsApp</a></div></nav><button class="menu-backdrop" type="button" aria-label="Menüyü kapat" hidden></button><a class="button header-cta" href="${phoneLink}">${icon('phone')} <span>Servis için ara</span></a></div></header>`;
const footer = `<footer class="footer"><div class="wrap footer-main"><div class="footer-brand"><a href="/" aria-label="Dost Teknik ana sayfa"><img class="footlogo" src="${logo}" width="408" height="164" alt="Dost Teknik Klima ve Beyaz Eşya Servisi"></a><p>Turgutreis merkezli Dost Teknik, Bodrum Yarımadası genelindeki klima ve beyaz eşya servis taleplerini değerlendirir.</p><span class="footer-social">Instagram · ${site.instagram}</span></div><div class="footer-col"><h2>Hizmetler</h2>${services.slice(0,6).map(x=>link(x.url,x.name)).join('')}${link('/hizmetler/','Tüm hizmetler','footer-all')}</div><div class="footer-col"><h2>Bölgeler</h2>${regions.slice(0,6).map(x=>link(x.url,x.name)).join('')}${link('/bolgeler/','Tüm bölgeler','footer-all')}</div><div class="footer-col"><h2>İletişim</h2><a href="${phoneLink}">${icon('phone')} ${site.phone}</a><a href="${whatsapp}" rel="noopener">${icon('chat')} WhatsApp</a><p>${icon('pin')} ${site.address}</p><p>${icon('clock')} ${site.hours}</p><a href="/iletisim.html">İletişim sayfası ${icon('arrow')}</a></div></div><div class="wrap footer-bottom"><span>© ${new Date().getFullYear()} Dost Teknik</span><nav aria-label="Yardımcı bağlantılar"><a href="/markalar/">Markalar</a><a href="/bilgi-merkezi/">Bilgi Merkezi</a><a href="/hakkimizda.html">Hakkımızda</a></nav></div></footer><div class="mobile-actions" aria-label="Hızlı iletişim"><a class="mobile-action mobile-action-call" href="${phoneLink}" aria-label="Dost Teknik'i hemen ara">${icon('phone')}<span>Hemen Ara</span></a><a class="mobile-action mobile-action-wa" href="${whatsapp}" rel="noopener" aria-label="Dost Teknik'e WhatsApp ile ulaş">${icon('chat')}<span>WhatsApp</span></a></div>`;

function render({path,title,description,h1,crumbs=[],content,schemas=[],image=null,isHome=false}) {
  const allSchemas = [businessSchema,crumbSchema([{name:'Ana Sayfa',url:'/'},...crumbs]),...schemas];
  const schemaTags = allSchemas.map(s=>`<script type="application/ld+json">${JSON.stringify(s).replace(/</g,'\\u003c')}</script>`).join('');
  const heroImage = image ? `<figure class="hero-visual"><img class="hero-photo" src="${image.src}" width="${image.width}" height="${image.height}" alt="${esc(image.alt)}" ${image.eager?'fetchpriority="high"':'loading="lazy"'}>${isHome?`<figcaption class="photo-caption"><span class="caption-mark">D</span><span><strong>Dost Teknik</strong><small>Akçaalan · Bodrum</small></span></figcaption>`:''}</figure>` : '';
  const canonical = absolute(path);
  const analytics = site.analyticsId ? `<script async src="https://www.googletagmanager.com/gtag/js?id=${esc(site.analyticsId)}"></script><script>window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments)}gtag('js',new Date());gtag('config','${esc(site.analyticsId)}');</script>` : '';
  const breadcrumb = crumbs.length?`<nav class="breadcrumbs" aria-label="Ekmek kırıntısı">${link('/','Ana Sayfa')}${crumbs.map(c=>`<span class="crumb-sep" aria-hidden="true">/</span>${link(c.url,c.name)}`).join('')}</nav>`:'';
  const hero = isHome
    ? `<section class="hero-home"><div class="wrap hero-home-grid"><div class="hero-copy"><p class="eyebrow">${icon('pin')} TURGUTREİS · BODRUM</p><p class="hero-label">KLİMA &amp; BEYAZ EŞYA TEKNİK SERVİSİ</p><h1>${esc(h1)}</h1><p class="lead">Klima ve ev tipi cihazlarınız için servis talebinizi doğrudan Dost Teknik’e iletin. Turgutreis’ten Bodrum Yarımadası genelinde.</p><div class="actions"><a class="button" href="${phoneLink}">${icon('phone')} Telefonla servis iste</a><a class="button button-whatsapp" href="${whatsapp}" rel="noopener">${icon('chat')} WhatsApp</a></div><div class="hero-facts"><span>${icon('pin')} Turgutreis merkezli</span><span>${icon('snow')} Bodrum Yarımadası</span><span>${icon('clock')} ${site.hours}</span></div></div>${heroImage}</div></section>`
    : `<section class="page-hero"><div class="wrap page-hero-inner">${breadcrumb}<p class="eyebrow">DOST TEKNİK <span>·</span> BODRUM</p><h1>${esc(h1)}</h1><p class="lead">${esc(description)}</p><div class="actions"><a class="button" href="${phoneLink}">${icon('phone')} Telefonla servis iste</a><a class="button button-light" href="${whatsapp}" rel="noopener">${icon('chat')} WhatsApp</a></div>${heroImage}</div></section>`;
  return `<!doctype html><html lang="tr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="${esc(canonical)}"><meta name="theme-color" content="#101a27"><meta property="og:type" content="website"><meta property="og:locale" content="tr_TR"><meta property="og:site_name" content="Dost Teknik"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${esc(canonical)}"><meta property="og:image" content="${absolute(image?.src||photoOutside)}"><link rel="icon" href="${logo}" type="image/webp"><link rel="stylesheet" href="/assets/site.css">${schemaTags}${analytics}</head><body>${siteHeader}<main id="main">${hero}${content}</main>${footer}<script src="/assets/site.js" defer></script></body></html>`;
}
function section(title,intro,body,cls='section') { return `<section class="${cls}"><div class="wrap"><div class="section-head"><p class="eyebrow">DOST TEKNİK <span>·</span> BODRUM</p><h2>${title}</h2>${intro?`<p>${intro}</p>`:''}</div>${body}</div></section>`; }
function faqSection(items) { return section('Sık sorulan sorular','Servis talebinden önce merak ettiklerinize kısa yanıtlar.',`<div class="faq-list">${items.map(([q,a])=>faq(q,a)).join('')}</div>`,'section section-faq'); }
function contactActions() { return `<div class="actions"><a class="button" href="${phoneLink}">${icon('phone')} Hemen ara · ${site.phone}</a><a class="button button-whatsapp" href="${whatsapp}" rel="noopener">${icon('chat')} WhatsApp</a></div>`; }
function serviceFaqs(item) { return [[`Servis talebi için ${item.name.toLowerCase()} konusunda hangi bilgileri paylaşmalıyım?`,'Cihazın türünü, marka-modelini, bulunduğunuz mahalleyi ve fark ettiğiniz belirtiyi iletin.'],['İşlem kapsamı ne zaman netleşir?','Cihazın durumu ve arıza belirtisi değerlendirildikten sonra uygun servis kapsamı açıklanır.'],['Bodrum Yarımadası’nda servis talebi oluşturabilir miyim?','Dost Teknik, Turgutreis merkezli olarak Bodrum Yarımadası genelindeki talepleri değerlendirir.']]; }
function regionFaqs(region) { return [[`${region.name} bölgesinde klima servisi için nasıl ulaşabilirim?`,`Dost Teknik’e telefonla veya WhatsApp’tan ulaşıp cihaz türü, belirti ve ${region.name} konum bilgisini iletin.`],['Hangi cihazlar için servis talebi alınıyor?','Klima ve ev tipi beyaz eşya servis başlıklarını hizmetler sayfasından inceleyebilirsiniz.']]; }
function brandFaqs(brand) { return [[`${brand.name} için servis talebinde hangi bilgileri paylaşmalıyım?`,'Cihazın model etiketindeki bilgileri, ürün türünü ve arıza belirtisini paylaşmanız ilk değerlendirmeye yardımcı olur.'],['Dost Teknik üretici yetkili servisi midir?','Dost Teknik bağımsız teknik servis hizmeti sunar; üretici yetkili servisi olduğu iddiasında bulunmaz.']]; }
function faqStructured(items) { return [faqSchema(items)]; }
function commonCTA(label='Servis ihtiyacınız mı var?') { return section(label,'Cihazın türünü, bulunduğunuz mahalleyi ve yaşadığınız belirtiyi paylaşın. Servis kapsamını birlikte netleştirelim.',`<div class="cta-panel"><div><p class="eyebrow">DOĞRUDAN İLETİŞİM</p><h3>Servis talebinizi Dost Teknik’e iletin</h3><p>Telefonla arayın veya WhatsApp’tan cihaz bilgilerini gönderin.</p></div>${contactActions()}</div>`,'section section-cta'); }
function localLinks(current=null) { return regions.filter(r=>r.slug!==current).map(r=>r); }
function serviceSchema(item) { return {'@context':'https://schema.org','@type':'Service','name':item.name,'serviceType':item.name,'provider':{'@type':'HVACBusiness','name':site.name,'telephone':site.phone},'areaServed':{'@type':'AdministrativeArea','name':'Bodrum Yarımadası'}}; }
function writePage(path,html) { const relative=path==='/'?'index.html':path.replace(/^\//,''); const target=join(out,relative.endsWith('/')?`${relative}index.html`:relative); return mkdir(dirname(target),{recursive:true}).then(()=>writeFile(target,html)); }

await rm(out,{recursive:true,force:true});
await mkdir(join(out,'assets/images'),{recursive:true});
await mkdir(join(out,'assets'),{recursive:true});
for (const f of ['DostTeknik_Logo_Yeni.jpg','DostTeknik_Disari.jpeg','DostTeknik_iceri.jpeg','dost-teknik-logo.webp','dost-teknik-isletme-dis.webp','dost-teknik-isletme-ici.webp']) await copyFile(join(root,'assets/images',f),join(out,'assets/images',f));
const css = await readFile(join(root,'assets/site.css'),'utf8'); await writeFile(join(out,'assets/site.css'),css);
const js = await readFile(join(root,'assets/site.js'),'utf8'); await writeFile(join(out,'assets/site.js'),js);

const trustItems = [
  ['pin','Yerel merkez','Akçaalan, Turgutreis'],['snow','Klima servisi','Bakım ve onarım'],
  ['appliance','Beyaz eşya','Ev tipi cihaz desteği'],['clock','Çalışma saati',site.hours]
];
const processSteps = [['01','Servis talebi','Telefon veya WhatsApp’tan bize ulaşın.'],['02','Cihaz bilgisi','Ürün türünü, marka-modeli ve belirtiyi paylaşın.'],['03','Teknik değerlendirme','Sorunu ve uygun servis kapsamını birlikte netleştirelim.'],['04','Servis süreci','Uygunluk ve işlem planı için sizinle iletişim kuralım.']];
const homeFaqs = [
 ['Hangi bölgelerde servis talebi oluşturabilirim?','Dost Teknik, Turgutreis merkezli olarak Bodrum Yarımadası genelindeki klima ve beyaz eşya servis taleplerini değerlendirir.'],
 ['Servis kaydı için hangi bilgileri paylaşmalıyım?','Cihaz türü, marka-model, arıza belirtisi ve bulunduğunuz mahalle ilk değerlendirmeye yardımcı olur.'],
 ['WhatsApp ile ulaşabilir miyim?','Evet. Sitedeki WhatsApp bağlantısı 0534 889 51 48 numarasına yönlenir.']
];
const featuredAreas = ['turgutreis','akyarlar','islamhaneleri','gumusluk','ortakent','bitez','yalikavak','gumbet'].map(slug=>regions.find(r=>r.slug===slug));
const featuredBrands = ['arcelik','beko','bosch','siemens','vestel','daikin','samsung','lg','hantech','mitsubishi-electric'].map(slug=>brands.find(b=>b.slug===slug));
const homeContent =
  `<section class="trust-strip" aria-label="Dost Teknik hizmet bilgileri"><div class="wrap trust-grid">${trustItems.map(([name,title,body])=>`<div class="trust-item"><span class="trust-icon">${icon(name)}</span><span><strong>${title}</strong><small>${body}</small></span></div>`).join('')}</div></section>` +
  section('Servis ihtiyacınıza uygun destek','Klima ve ev tipi cihazlar için ayrı servis başlıklarını inceleyin.',`${serviceCards(services.slice(0,6))}<div class="section-link">${link('/hizmetler/','Tüm hizmetleri görüntüle','text-link')}</div>`) +
  section('Yerel işletme. Doğrudan iletişim.','Dost Teknik’in gerçek işletme alanını ve adresini görün.',`<div class="editorial-grid"><div class="editorial-copy"><p class="eyebrow">DOST TEKNİK · AKÇAALAN</p><h3>Turgutreis’ten Bodrum Yarımadası’na</h3><p>İşletmemiz Akçaalan Mahallesi Zübeyde Hanım Caddesi’ndedir. Servis talebinizi doğrudan bize iletin; cihaz ve arıza bilgilerini birlikte değerlendirelim.</p><p class="address-line">${icon('pin')} ${site.address}</p>${link('/hakkimizda.html','İşletmemizi tanıyın','text-link')}</div><div class="photo-stack"><img class="editorial-main" src="${photoInside}" width="1200" height="1600" loading="lazy" alt="Dost Teknik işletme iç mekânında klima ürünlerinin sergilendiği alan"><div class="editorial-note"><span class="caption-mark">D</span><span><strong>Dost Teknik</strong><small>Klima &amp; beyaz eşya servisi</small></span></div></div></div>`) +
  section('Servis süreci nasıl ilerler?','İlk görüşmeden servis planına kadar temel adımlar.',`<ol class="process-grid">${processSteps.map(([num,title,body])=>`<li class="process-step"><span class="process-number">${num}</span><h3>${title}</h3><p>${body}</p></li>`).join('')}</ol>`) +
  section('Servis verdiğimiz markalar','Marka sayfalarında cihaz grupları ve hizmet bölgeleri hakkında bilgi alın.',`<div class="brand-chips">${featuredBrands.map(b=>link(b.url,b.name,'brand-chip')).join('')}</div><div class="section-link">${link('/markalar/','60 markanın tamamını görüntüle','text-link')}</div>`) +
  section('Bodrum Yarımadası genelinde','Öne çıkan hizmet bölgelerini görün; tüm bölgeler ayrı sayfalarda listelenmiştir.',`<div class="area-grid">${featuredAreas.map((r,i)=>`<a class="area-card${i===0?' area-card-main':''}" href="${r.url}"><span class="area-count">${String(i+1).padStart(2,'0')}</span><strong>${r.name}</strong>${icon('arrow')}</a>`).join('')}</div><div class="section-link">${link('/bolgeler/','Tüm hizmet bölgelerini görüntüle','text-link')}</div>`) +
  section('Bilgi merkezi','Klima ve ev tipi cihazlarla ilgili pratik rehberleri inceleyin.',`<div class="guide-grid">${guides.slice(0,3).map(g=>`<a class="guide-card" href="${g.url}"><span class="guide-label">TEKNİK REHBER</span><h3>${g.title}</h3><p>${g.description}</p><span class="text-link">Rehberi oku ${icon('arrow')}</span></a>`).join('')}</div><div class="section-link">${link('/bilgi-merkezi/','Tüm rehberlere git','text-link')}</div>`) +
  faqSection(homeFaqs) + commonCTA();
await writePage('/',render({path:'/',title:'Turgutreis Klima Servisi ve Bodrum Beyaz Eşya | Dost Teknik',description:'Dost Teknik; Turgutreis merkezli klima bakım, onarım ve beyaz eşya servis desteğiyle Bodrum Yarımadası genelinde hizmet verir.',h1:'Turgutreis Klima Servisi · Bodrum’da Teknik Destek',content:homeContent,image:{src:photoOutside,width:1086,height:1448,alt:'Dost Teknik klima ve beyaz eşya servis işletmesinin dış görünümü',eager:true},isHome:true,schemas:[faqSchema(homeFaqs)]}));

const directoryPages = [
 {path:'/hizmetler/',name:'Hizmetler',title:'Klima ve Beyaz Eşya Hizmetleri | Dost Teknik',desc:'Klima tamiri, bakım, montaj ve Bodrum’da beyaz eşya servis hizmetlerini inceleyin.',items:services,type:'services'},
 {path:'/bolgeler/',name:'Hizmet Bölgeleri',title:'Bodrum Klima Servisi Bölgeleri | Dost Teknik',desc:'Turgutreis merkezli hizmet verdiğimiz Bodrum Yarımadası mahalle ve bölgelerini inceleyin.',items:regions,type:'regions'},
 {path:'/markalar/',name:'Markalar',title:'Klima ve Beyaz Eşya Markaları | Dost Teknik',desc:'Dost Teknik’in klima ve beyaz eşya servis kapsamındaki marka sayfalarını inceleyin.',items:brands,type:'brands'},
 {path:'/bilgi-merkezi/',name:'Bilgi Merkezi',title:'Klima ve Beyaz Eşya Rehberleri | Dost Teknik',desc:'Klima ve ev tipi cihazların bakımı, arıza belirtileri ve servis hazırlığı hakkında rehberler.',items:guides,type:'guides'}
];
for (const d of directoryPages) {
 const bodyContent=d.type==='services'?serviceCards(d.items)
  :d.type==='regions'?`<div class="area-grid">${d.items.map((r,i)=>`<a class="area-card${i===0?' area-card-main':''}" href="${r.url}"><span class="area-count">BÖLGE ${String(i+1).padStart(2,'0')}</span><strong>${r.name}</strong>${icon('arrow')}</a>`).join('')}</div>`
  :d.type==='brands'?`<div class="brand-chips">${d.items.map(b=>link(b.url,b.name,'brand-chip')).join('')}</div>`
  :`<div class="guide-grid guide-grid-directory">${d.items.map(g=>`<a class="guide-card" href="${g.url}"><span class="guide-label">TEKNİK REHBER</span><h3>${g.title}</h3><p>${g.description}</p><span class="text-link">Rehberi oku ${icon('arrow')}</span></a>`).join('')}</div>`;
 const body=section(d.name, d.desc, bodyContent);
 await writePage(d.path,render({path:d.path,title:d.title,description:d.desc,h1:d.name,crumbs:[{name:d.name,url:d.path}],content:body}));
}

for (const item of services) {
 const desc=`${item.description} Turgutreis ve Bodrum Yarımadası için Dost Teknik servis bilgileri.`;
 const questions=serviceFaqs(item);
 const text=section('Servis kapsamı',item.description,`<div class="prose"><p>${esc(item.description)} Talep sırasında cihazın marka-modelini, ekrandaki uyarı kodunu ve sorunun ne zaman başladığını belirtin. Bu bilgiler ilk değerlendirmeyi kolaylaştırır.</p><h3>Servis öncesi neleri paylaşabilirsiniz?</h3><p>Cihazın türü, bulunduğunuz bölge, arıza belirtisi ve daha önce yapılan işlemleri not edin. Güvenliğinizden emin olmadığınız müdahaleleri kendiniz yapmayın.</p><h3>Bodrum’da hizmet planlaması</h3><p>Dost Teknik, Turgutreis merkezinden Bodrum Yarımadası genelindeki talepleri değerlendirir. Uygunluk ve işlem kapsamı cihazın incelenmesiyle belirlenir.</p></div>`) + section('İlgili hizmetler','Benzer servis ihtiyaçları için diğer hizmetlerimizi inceleyin.',serviceCards(services.filter(x=>x.slug!==item.slug).slice(0,6))) + section('İlgili markalar','Cihaz markanıza göre servis kapsamını ve bölge bağlantılarını görüntüleyin.',`<div class="brand-chips">${brands.slice(0,10).map(b=>link(b.url,b.name,'brand-chip')).join('')}</div>`) + section('İlgili bölgeler','Servis talebiniz için bulunduğunuz bölgenin sayfasını seçin.',cards(regions.slice(0,8))) + faqSection(questions) + commonCTA();
 await writePage(item.url,render({path:item.url,title:`${item.name} Turgutreis & Bodrum | Dost Teknik`,description:desc,h1:`Turgutreis ${item.name}`,crumbs:[{name:'Hizmetler',url:'/hizmetler/'},{name:item.name,url:item.url}],content:text,schemas:[serviceSchema(item),...faqStructured(questions)]}));
}

for (const region of regions) {
 const desc=`${region.name} klima servisi ve beyaz eşya teknik servis desteği. Turgutreis merkezli Dost Teknik’e ulaşın; Bodrum Yarımadası’nda servis talebinizi paylaşın.`;
 const combos=brandRegionPairs.filter(p=>p.region.slug===region.slug).map(p=>({name:`${p.brand.name} servisi`,url:`/servis/${region.slug}/${p.brand.slug}-servisi.html`}));
  const questions=regionFaqs(region);
  const content=section(`${region.name}’da klima ve beyaz eşya desteği`, `Bölgenizdeki servis talebinizi cihaz ve arıza bilgileriyle iletin. İşlem kapsamı cihaz incelendikten sonra netleşir.`, `<div class="prose"><p>Dost Teknik, Akçaalan’daki işletmesinden Turgutreis ve Bodrum Yarımadası genelindeki klima ve beyaz eşya servis taleplerini değerlendirir. ${esc(region.name)} bölgesindeki talebiniz için cihaz türünü, marka-modeli ve gözlemlediğiniz belirtiyi paylaşabilirsiniz.</p><h3>Klima bakım ve onarım</h3><p>Soğutma performansı, su akıtma, ses, bakım, montaj ve temizlik ihtiyaçları cihazın durumuna göre ele alınır.</p><h3>Beyaz eşya teknik servis</h3><p>Buzdolabı, çamaşır ve bulaşık makinesi gibi cihazlardaki belirtiler için ilgili servis sayfalarını inceleyin.</p></div>`) + section(`${region.name} için hizmet başlıkları`,'Klima ve ev cihazları için servis kapsamını inceleyin.',serviceCards(services.slice(0,8))) + (combos.length?section('Marka bazlı servis sayfaları',`${region.name} için referans HTML bağlantılarında doğrulanan marka servis sayfaları.`,cards(combos)): '') + section('Yakın hizmet bölgeleri','Bodrum Yarımadası’ndaki diğer hizmet bölgeleri.',cards(localLinks(region.slug).slice(0,8))) + faqSection(questions) + commonCTA(`Dost Teknik’e ${region.name} servis talebi iletin`);
  await writePage(region.url,render({path:region.url,title:`${region.name} Klima Servisi & Beyaz Eşya | Dost Teknik`,description:desc,h1:`${region.name} Klima Servisi & Beyaz Eşya Tamiri`,crumbs:[{name:'Hizmet Bölgeleri',url:'/bolgeler/'},{name:region.name,url:region.url}],content,image:region.slug==='turgutreis'?{src:photoOutside,width:1086,height:1448,alt:'Dost Teknik Bodrum klima servis işletmesi dış görünümü'}:null,schemas:faqStructured(questions)}));
}

for (const brand of brands) {
 const desc=`${brand.name} klima ve beyaz eşya servis desteği. Arıza belirtisi ve cihaz modelini Dost Teknik’e iletin; Bodrum genelindeki hizmet bölgelerini inceleyin.`;
 const linked=linkedRegionSlugs.map(s=>regions.find(r=>r.slug===s));
  const questions=brandFaqs(brand.name);
  const content=section(`${brand.name} cihazlarında servis`, `Marka adı, tek başına üretici veya yetkili servis bağlantısı anlamına gelmez. Dost Teknik bağımsız teknik servis hizmeti sunar.`, `<div class="prose"><p>${esc(brand.name)} cihazınızla ilgili servis talebinde model bilgisini ve arıza belirtisini iletin. Cihazın türü, yaşı ve kullanım koşulları değerlendirme sırasında dikkate alınır.</p><h3>Servis talebi için hazırlık</h3><p>Model etiketi, hata kodu ve sorunun ne zaman başladığına dair bilgi paylaşın. Onarım ve parça gereksinimi cihazın kontrolünden sonra belirlenir.</p><h3>Bodrum’da hizmet alanı</h3><p>Turgutreis merkezli servis talebinizi Bodrum Yarımadası’ndaki bölgenizle birlikte iletin.</p></div>`) + section('İlgili cihaz hizmetleri','Cihaz türünüze uygun hizmet detayına geçin.',serviceCards(services.filter(s=>/klima|buzdolabi|camasir|bulasik|beyaz|kurutma|ankastre/i.test(s.slug)).slice(0,6))) + section(`${brand.name} servis bölgeleri`,'Aşağıdaki bağlantılar bu marka detay sayfasında gerçek bağlantı olarak görülen bölgelerdir.',cards(linked)) + faqSection(questions) + commonCTA();
  await writePage(brand.url,render({path:brand.url,title:`${brand.name} Servisi Turgutreis & Bodrum | Dost Teknik`,description:desc,h1:`Turgutreis ${brand.name} Klima & Beyaz Eşya Servisi`,crumbs:[{name:'Markalar',url:'/markalar/'},{name:brand.name,url:brand.url}],content,schemas:faqStructured(questions)}));
}

for (const pair of brandRegionPairs) {
 const path=`/servis/${pair.region.slug}/${pair.brand.slug}-servisi.html`;
 const desc=`${pair.region.name} ${pair.brand.name} klima ve beyaz eşya servis desteği. Cihaz modeli ve arıza belirtisiyle Dost Teknik’e ulaşın.`;
  const questions=[[`${pair.region.name} bölgesinde ${pair.brand.name} cihazı için nasıl servis isteyebilirim?`,`Dost Teknik’i arayıp veya WhatsApp’tan yazarak cihaz modeli, belirti ve ${pair.region.name} konum bilgisini paylaşın.`],['Dost Teknik bu markanın yetkili servisi midir?','Dost Teknik bağımsız teknik servis hizmeti sunar; üretici yetkili servisi olduğu iddiasında bulunmaz.']];
  const content=section(`${pair.region.name} bölgesinde ${pair.brand.name} cihaz desteği`, 'Cihaz türü ve arıza belirtilerine göre servis talebinizi değerlendiriyoruz.', `<div class="prose"><p>${esc(pair.region.name)} bölgesindeki ${esc(pair.brand.name)} cihazınız için marka-modeli ve arıza belirtisini paylaşın. Dost Teknik bağımsız teknik servis hizmeti sunar; üretici yetkili servisi iddiasında bulunmaz.</p><h3>İlk değerlendirme için</h3><p>Cihazın model etiketini, hata kodunu ve sorunun başlangıç zamanını not edin. İşlem ve parça kapsamı cihazın kontrol edilmesinden sonra netleşir.</p><p>Klima bakım, onarım ve beyaz eşya servis seçenekleri için ilgili hizmet sayfalarımıza göz atabilirsiniz.</p></div>`) + section('İlgili servis başlıkları','Cihaz ihtiyacınıza göre hizmet detaylarını görüntüleyin.',serviceCards(services.slice(0,6))) + section('Diğer doğrulanmış hizmet bölgeleri','Bu marka için referans marka sayfasında bağlantısı görülen bölgeler.',cards(linkedRegionSlugs.filter(s=>s!==pair.region.slug).slice(0,6).map(s=>regions.find(r=>r.slug===s)))) + faqSection(questions) + commonCTA();
  await writePage(path,render({path,title:`${pair.region.name} ${pair.brand.name} Servisi | Dost Teknik`,description:desc,h1:`${pair.region.name} ${pair.brand.name} Servisi`,crumbs:[{name:'Markalar',url:'/markalar/'},{name:pair.brand.name,url:pair.brand.url},{name:pair.region.name,url:`/bolgeler/${pair.region.slug}-klima-servisi.html`}],content,schemas:faqStructured(questions)}));
}

for (const guide of guides) {
 const desc=guide.description;
 const content=section('Belirtiyi doğru tanımlayın',guide.description,`<article class="prose"><p>${esc(guide.description)} Cihazın çalışma biçimi, ortam koşulları ve bakım geçmişi aynı belirtiyi farklı nedenlerle ortaya çıkarabilir.</p><h3>Güvenli biçimde kontrol edebilecekleriniz</h3><p>Kullanım kılavuzundaki temel adımlara göz atın; fiş, filtre veya erişilebilir ayarları cihazın talimatlarına uygun şekilde kontrol edin. Cihazı açmayın ve elektrikli ya da soğutucu sistem bileşenlerine müdahale etmeyin.</p><h3>Ne zaman teknik servis gerekir?</h3><p>Belirti devam ediyorsa, olağan dışı koku/ses varsa veya cihaz güvenli çalışmıyorsa kullanımı durdurup teknik servisle görüşün. Servis kaydı için marka-model, belirti ve konum bilgisini hazırlayın.</p><h3>Bodrum ve Turgutreis için not</h3><p>Bodrum Yarımadası’ndaki çevre koşulları ve dönemsel kullanım, bakım planını etkileyebilir. Cihazın bulunduğu ortamı da servis talebinde paylaşın.</p></article>`) + section('İlgili hizmetler','Belirti cihaz servis gerektiriyorsa ilgili kapsamı inceleyin.',cards(services.slice(0,6))) + section('Daha fazla teknik rehber','Cihaz kullanımı ve bakımı hakkında diğer yazılar.',cards(guides.filter(g=>g.slug!==guide.slug).slice(0,6),g=>g.title)) + commonCTA();
 await writePage(guide.url,render({path:guide.url,title:`${guide.title} | Dost Teknik`,description:desc,h1:guide.title,crumbs:[{name:'Bilgi Merkezi',url:'/bilgi-merkezi/'},{name:guide.title,url:guide.url}],content}));
}

const aboutPath='/hakkimizda.html', contactPath='/iletisim.html';
await writePage(aboutPath,render({path:aboutPath,title:'Dost Teknik Hakkında | Turgutreis, Bodrum',description:'Dost Teknik’in Bodrum Akçaalan’daki işletmesi, servis yaklaşımı ve Bodrum Yarımadası hizmet alanı hakkında bilgi alın.',h1:'Turgutreis Merkezli Klima & Beyaz Eşya Teknik Servis',crumbs:[{name:'Hakkımızda',url:aboutPath}],content:section('Yerel servis, açık iletişim','Dost Teknik, Akçaalan Mahallesi’ndeki işletmesinden Bodrum Yarımadası’ndaki servis taleplerini değerlendirir.',`<div class="split"><img src="${photoInside}" width="1200" height="1600" loading="lazy" alt="Dost Teknik işletmesinin klima cihazlarının sergilendiği iç mekânı"><div class="prose"><h3>Hizmet yaklaşımımız</h3><p>Önce cihazın belirtisini ve modelini öğreniyor, servis kapsamını kontrol sonrasında netleştiriyoruz. Randevu ve işlem uygunluğu için doğrudan telefonla görüşebilirsiniz.</p><h3>Hizmet alanı</h3><p>Turgutreis merkezli olarak Bodrum Yarımadası genelindeki klima ve beyaz eşya servis taleplerini alıyoruz.</p><p><strong>Adres:</strong> ${site.address}</p></div></div>`) + section('Neler için servis alabilirsiniz?','Klima ve beyaz eşya servis başlıklarını inceleyin.',cards(services.slice(0,8))) + commonCTA()}));
await writePage(contactPath,render({path:contactPath,title:'Dost Teknik İletişim ve Servis Kaydı | Bodrum',description:`Dost Teknik’e ${site.phone} numarasından ulaşın. Adres: ${site.address}. Çalışma saatleri ${site.hours}.`,h1:'Turgutreis Klima & Beyaz Eşya Servis Kaydı',crumbs:[{name:'İletişim',url:contactPath}],content:section('Servis için bize ulaşın','Cihaz türünü, marka-modeli ve arıza belirtisini paylaşarak servis talebinizi iletin.',`<div class="contact-grid"><div class="prose"><h3>Telefon</h3><p><a class="contact-phone" href="${phoneLink}">${site.phone}</a></p><h3>WhatsApp</h3><p><a href="${whatsapp}" rel="noopener">WhatsApp’tan yazın</a></p><h3>Adres</h3><p>${site.address}</p><h3>Çalışma saatleri</h3><p>${site.hours}</p><p>Instagram: ${site.instagram}</p>${site.mapsUrl?`<p><a href="${esc(site.mapsUrl)}">Haritada görüntüle</a></p>`:''}</div><img src="${photoOutside}" width="1086" height="1448" loading="lazy" alt="Dost Teknik servis işletmesinin dış cephe görünümü"></div>`) + section('Hizmet bölgeleri','Servis alanımızdaki mahalleleri inceleyin.',cards(regions))}));

const sitemapUrls=[...new Set(knownUrls)];
const sitemap=`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${sitemapUrls.map(p=>`  <url><loc>${esc(absolute(p))}</loc></url>`).join('\n')}\n</urlset>\n`;
await writeFile(join(out,'sitemap.xml'),sitemap);
await writeFile(join(out,'robots.txt'),`User-agent: *\nAllow: /\nSitemap: ${absolute('/sitemap.xml')}\n`);
await writeFile(join(out,'404.html'),render({path:'/404.html',title:'Sayfa Bulunamadı | Dost Teknik',description:'Aradığınız sayfa bulunamadı. Dost Teknik ana sayfasına veya hizmet bölgelerine geçin.',h1:'Bu sayfayı bulamadık',content:section('Aradığınız sayfa mevcut değil','Adres değişmiş veya kaldırılmış olabilir.',`<div class="actions">${link('/','Ana sayfaya dön','button')}${link('/hizmetler/','Hizmetleri incele','button secondary')}${link('/bolgeler/','Bölgeleri görüntüle','button secondary')}</div>`)}));
await writeFile(join(out,'.nojekyll'),'');
console.log(`Build complete: ${sitemapUrls.length} indexable URLs; ${brandRegionPairs.length} verified brand/region pages.`);
