import { mkdir, rm, writeFile, copyFile, readFile } from 'node:fs/promises';
import { dirname, resolve, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { site, services, regions, brands, guides, enrichedGuides, serviceDetails, serviceRelatedMap, linkedRegionSlugs, brandRegionPairs, knownUrls } from './data.mjs';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const out = join(root, 'dist');
const base = (process.env.SITE_URL || site.siteUrl).replace(/\/$/, '');
const esc = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const absolute = path => `${base}${path}`;
const phoneLink = `tel:+${site.phoneDigits}`;
const whatsapp = `https://wa.me/${site.phoneDigits}`;
const whatsappFor = message => `${whatsapp}?text=${encodeURIComponent(message)}`;
const logo = '/assets/images/dost-teknik-logo.webp';
const photoOutside = '/assets/images/dost-teknik-isletme-dis.webp';
const photoInside = '/assets/images/dost-teknik-isletme-ici.webp';
const icons = {
  phone:'<path d="M22 16.9v3a2 2 0 0 1-2.2 2A19.8 19.8 0 0 1 11.2 19a19.4 19.4 0 0 1-6-6A19.8 19.8 0 0 1 2.1 4.2 2 2 0 0 1 4.1 2h3a2 2 0 0 1 2 1.7l.5 2.7a2 2 0 0 1-.6 1.8L7.5 9.7a16 16 0 0 0 6 6l1.5-1.5a2 2 0 0 1 1.8-.6l2.7.5a2 2 0 0 1 1.7 2.8Z"/>',
  chat:'<path d="M21 11.5a8.4 8.4 0 0 1-12.4 7.4L3 20l1.2-5.3A8.5 8.5 0 1 1 21 11.5Z"/><path d="M8 9.5c.7 2.2 2.3 3.8 4.5 4.5"/>',
  snow:'<path d="M12 2v20M4 7l16 10M20 7 4 17M8.5 4.5 12 2l3.5 2.5M8.5 19.5 12 22l3.5-2.5M3.5 10 4 7l3.5-.5M16.5 17.5 20 17l.5-3M20 7l.5 3-3.5.5M4 17l-.5-3 3.5-.5"/>',
  appliance:'<rect x="4" y="2.5" width="16" height="19" rx="2"/><path d="M4 8h16M8 5.3h.01M11 5.3h.01M8 11v7M12 11v7M16 11v7"/>',
  pin:'<path d="M20 10c0 5-8 12-8 12S4 15 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/>',
  clock:'<circle cx="12" cy="12" r="9.5"/><path d="M12 6.5V12l4 2"/>',
  arrow:'<path d="M5 12h14M13 6l6 6-6 6"/>',
  menu:'<path d="M4 6h16M4 12h16M4 18h16"/>',
  wrench:'<path d="M14.7 6.3a5 5 0 0 0-6.6 6.6L2.5 18.5a2.1 2.1 0 0 0 3 3l5.6-5.6a5 5 0 0 0 6.6-6.6L14.5 12 12 9.5l2.7-3.2Z"/>',
  installation:'<path d="M3 21h18M5 21V5l7-3 7 3v16M9 10h6M9 14h6M10 21v-4h4v4"/>',
  gauge:'<path d="M4 18a8 8 0 1 1 16 0M12 14l4-5M7 18h.01M17 18h.01M12 6v.01"/><circle cx="12" cy="14" r="1"/>',
  clean:'<path d="M4 20 15.5 8.5M14 4l6 6M4 20l-1 1M8 16l-2-2M11 13l-2-2M17 7l-2-2"/><path d="M4 5h4M6 3v4M18 15h4M20 13v4"/>',
  circuit:'<rect x="5" y="5" width="14" height="14" rx="2"/><path d="M9 9h6v6H9zM2 8h3M2 12h3M2 16h3M19 8h3M19 12h3M19 16h3M8 2v3M12 2v3M16 2v3M8 19v3M12 19v3M16 19v3"/>',
  vrf:'<rect x="3" y="3" width="8" height="8" rx="1"/><rect x="13" y="3" width="8" height="8" rx="1"/><rect x="8" y="13" width="8" height="8" rx="1"/><path d="M7 11v2h10v-2M12 13v-2"/>',
  multi:'<rect x="3" y="4" width="8" height="6" rx="1"/><rect x="13" y="4" width="8" height="6" rx="1"/><path d="M4 14h16M6 14v5M18 14v5M4 19h4M16 19h4"/>',
  fridge:'<rect x="5" y="2" width="14" height="20" rx="2"/><path d="M5 11h14M9 6v2M9 14v3"/>',
  washer:'<rect x="4" y="2" width="16" height="20" rx="2"/><circle cx="12" cy="13" r="5"/><path d="M8 5h.01M11 5h.01M15 5h1"/>',
  dishwasher:'<rect x="4" y="2" width="16" height="20" rx="2"/><path d="M4 7h16M8 4.5h.01M12 4.5h.01M8 11h8M8 15h8M8 19h8"/>',
  dryer:'<rect x="4" y="2" width="16" height="20" rx="2"/><circle cx="12" cy="13" r="5"/><path d="M8 5h.01M12 5h.01M16 5h.01M10 12c1-1 3-1 4 0"/>',
  freezer:'<rect x="4" y="2" width="16" height="20" rx="2"/><path d="M4 10h16M8 6v1M8 14v3"/>',
  oven:'<rect x="3" y="3" width="18" height="18" rx="2"/><path d="M3 8h18M7 5.5h.01M11 5.5h.01M8 13h8v5H8z"/>',
  chevron:'<path d="m6 9 6 6 6-6"/>'
};
const icon = (name, cls='') => `<svg class="icon${cls?` ${cls}`:''}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[name]||icons.arrow}</svg>`;
const faq = (q,a) => `<details class="faq"><summary>${esc(q)}${icon('chevron')}</summary><p>${esc(a)}</p></details>`;
const faqSchema = items => ({'@context':'https://schema.org','@type':'FAQPage',mainEntity:items.map(([q,a])=>({'@type':'Question',name:q,acceptedAnswer:{'@type':'Answer',text:a}}))});
const link = (href,label,cls='') => `<a${cls?` class="${cls}"`:''} href="${esc(href)}">${esc(label)}</a>`;
const cards = (items, label=x=>x.name) => `<div class="cards">${items.map(x=>`<a class="card" href="${esc(x.url)}"><span>${esc(label(x))}</span>${icon('arrow','card-arrow')}</a>`).join('')}</div>`;
const serviceCards = items => `<div class="service-grid">${items.map(item=>`<a class="service-card" href="${item.url}"><span class="service-icon">${icon(serviceDetails[item.slug]?.icon||'wrench')}</span><span class="service-card-copy"><strong>${esc(item.name)}</strong><small>${esc(item.description)}</small><span class="text-link">Hizmeti incele ${icon('arrow')}</span></span></a>`).join('')}</div>`;
const crumbSchema = crumbs => ({'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:crumbs.map((c,i)=>({'@type':'ListItem',position:i+1,name:c.name,item:absolute(c.url)}))});
const businessSchema = {
  '@context':'https://schema.org','@type':'HVACBusiness','name':site.name,'url':base,'image':[absolute(photoOutside),absolute(photoInside)],'logo':absolute(logo),
  'telephone':site.phone,'address':{'@type':'PostalAddress',...site.addressParts},
  'areaServed':regions.map(r=>({'@type':'Place','name':r.name}))
};
const navLinks = `<a href="/hizmetler/">Hizmetler</a><a href="/bolgeler/">Bölgeler</a><a href="/markalar/">Markalar</a><a href="/bilgi-merkezi/">Bilgi Merkezi</a><a href="/hakkimizda.html">Hakkımızda</a><a href="/iletisim.html">İletişim</a>`;
const navLinksFor = path => navLinks.replace(/<a href="([^"]+)">([^<]+)<\/a>/g,(_,href,label)=>{
  const isDirectory=href.endsWith('/')&&href!=='/';
  const current=isDirectory?path.startsWith(href):path===href;
  return `<a href="${href}"${current?' class="nav-current" aria-current="location"':''}>${label}</a>`;
});
const siteHeader = `<a class="skip" href="#main">İçeriğe geç</a><div class="topbar"><div class="wrap top-inner"><span>Turgutreis merkezli · Bodrum Yarımadası genelinde servis</span><span class="top-contact">${icon('clock')} ${site.hours}<a href="${phoneLink}">${icon('phone')} ${site.phone}</a></span></div></div><header class="header"><div class="wrap nav"><a class="brand" href="/" aria-label="Dost Teknik ana sayfa"><img src="${logo}" width="408" height="164" alt="Dost Teknik Klima ve Beyaz Eşya Servisi"></a><button class="nav-toggle" aria-expanded="false" aria-controls="primary-nav" aria-label="Menüyü aç">${icon('menu','menu-glyph')}<span>Menü</span></button><nav id="primary-nav" aria-label="Ana menü"><div class="drawer-heading"><span>Menü</span><button class="menu-close" type="button" aria-label="Menüyü kapat">×</button></div>${navLinks}<div class="drawer-actions"><a class="button" href="${phoneLink}">${icon('phone')} Hemen ara</a><a class="button button-whatsapp" href="${whatsapp}" rel="noopener">${icon('chat')} WhatsApp</a></div></nav><button class="menu-backdrop" type="button" aria-label="Menüyü kapat" hidden></button><a class="button header-cta" href="${phoneLink}">${icon('phone')} <span>Servis için ara</span></a><a class="button button-whatsapp header-whatsapp" href="${whatsapp}" rel="noopener" aria-label="WhatsApp ile servis talebi">${icon('chat')}<span>WhatsApp</span></a></div></header>`;
const footer = `<footer class="footer"><div class="wrap footer-main"><div class="footer-brand"><a href="/" aria-label="Dost Teknik ana sayfa"><img class="footlogo" src="${logo}" width="408" height="164" alt="Dost Teknik Klima ve Beyaz Eşya Servisi"></a><p>Turgutreis merkezli Dost Teknik, Bodrum Yarımadası genelindeki klima ve beyaz eşya servis taleplerini değerlendirir.</p><span class="footer-social">Instagram · ${site.instagram}</span></div><div class="footer-col"><h2>Hizmetler</h2>${services.slice(0,6).map(x=>link(x.url,x.name)).join('')}${link('/hizmetler/','Tüm hizmetler','footer-all')}</div><div class="footer-col"><h2>Bölgeler</h2>${regions.slice(0,6).map(x=>link(x.url,x.name)).join('')}${link('/bolgeler/','Tüm bölgeler','footer-all')}</div><div class="footer-col"><h2>İletişim</h2><a href="${phoneLink}">${icon('phone')} ${site.phone}</a><a href="${whatsapp}" rel="noopener">${icon('chat')} WhatsApp</a><p>${icon('pin')} ${site.address}</p><p>${icon('clock')} ${site.hours}</p><a href="/iletisim.html">İletişim sayfası ${icon('arrow')}</a></div></div><div class="wrap footer-bottom"><span>© ${new Date().getFullYear()} Dost Teknik</span><nav aria-label="Yardımcı bağlantılar"><a href="/markalar/">Markalar</a><a href="/bilgi-merkezi/">Bilgi Merkezi</a><a href="/hakkimizda.html">Hakkımızda</a></nav></div></footer><div class="mobile-actions" aria-label="Hızlı iletişim"><a class="mobile-action mobile-action-call" href="${phoneLink}" aria-label="Dost Teknik'i hemen ara">${icon('phone')}<span>Hemen Ara</span></a><a class="mobile-action mobile-action-wa" href="${whatsapp}" rel="noopener" aria-label="Dost Teknik'e WhatsApp ile ulaş">${icon('chat')}<span>WhatsApp</span></a></div>`;

function render({path,title,description,h1,crumbs=[],content,schemas=[],image=null,isHome=false,whatsappMessage=null}) {
  const is404 = path === '/404.html';
  const allSchemas = is404 ? [] : [businessSchema,crumbSchema([{name:'Ana Sayfa',url:'/'},...crumbs]),...schemas];
  const schemaTags = allSchemas.map(s=>`<script type="application/ld+json">${JSON.stringify(s).replace(/</g,'\\u003c')}</script>`).join('');
  const heroImage = image ? `<figure class="hero-visual"><img class="hero-photo" src="${image.src}" width="${image.width}" height="${image.height}" alt="${esc(image.alt)}" ${image.eager?'fetchpriority="high"':'loading="lazy"'}>${isHome?`<figcaption class="photo-caption"><span class="caption-mark">D</span><span><strong>Dost Teknik</strong><small>Akçaalan · Bodrum</small></span></figcaption>`:''}</figure>` : '';
  const canonical = absolute(path);
  const pageWhatsapp = whatsappMessage ? whatsappFor(whatsappMessage) : whatsapp;
  const indexingMeta = is404 ? '<meta name="robots" content="noindex,follow">' : '';
  const analytics = site.analyticsId ? `<script async src="https://www.googletagmanager.com/gtag/js?id=${esc(site.analyticsId)}"></script><script>window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments)}gtag('js',new Date());gtag('config','${esc(site.analyticsId)}');</script>` : '';
  const breadcrumb = crumbs.length?`<nav class="breadcrumbs" aria-label="Ekmek kırıntısı">${link('/','Ana Sayfa')}${crumbs.map(c=>`<span class="crumb-sep" aria-hidden="true">/</span>${link(c.url,c.name)}`).join('')}</nav>`:'';
  const hero = isHome
    ? `<section class="hero-home"><div class="wrap hero-home-grid"><div class="hero-copy"><p class="eyebrow">${icon('pin')} TURGUTREİS · BODRUM</p><p class="hero-label">KLİMA &amp; BEYAZ EŞYA TEKNİK SERVİSİ</p><h1>${esc(h1)}</h1><p class="lead">Klima ve ev tipi cihazlarınız için servis talebinizi doğrudan Dost Teknik’e iletin. Turgutreis’ten Bodrum Yarımadası genelinde.</p><div class="actions"><a class="button" href="${phoneLink}">${icon('phone')} Telefonla servis iste</a><a class="button button-whatsapp" href="${pageWhatsapp}" rel="noopener">${icon('chat')} WhatsApp</a></div><div class="hero-facts"><span>${icon('pin')} Turgutreis merkezli</span><span>${icon('snow')} Bodrum Yarımadası</span><span>${icon('clock')} ${site.hours}</span></div></div>${heroImage}</div></section>`
    : `<section class="page-hero"><div class="wrap page-hero-inner">${breadcrumb}<p class="eyebrow">DOST TEKNİK <span>·</span> BODRUM</p><h1>${esc(h1)}</h1><p class="lead">${esc(description)}</p><div class="actions"><a class="button" href="${phoneLink}">${icon('phone')} Telefonla servis iste</a><a class="button button-light" href="${pageWhatsapp}" rel="noopener">${icon('chat')} WhatsApp</a></div>${heroImage}</div></section>`;
  const headerMarkup=siteHeader.replace(navLinks,navLinksFor(path));
  return `<!doctype html><html lang="tr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(description)}">${indexingMeta}${is404?'':`<link rel="canonical" href="${esc(canonical)}">`}<meta name="theme-color" content="#101a27"><meta property="og:type" content="website"><meta property="og:locale" content="tr_TR"><meta property="og:site_name" content="Dost Teknik"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}">${is404?'':`<meta property="og:url" content="${esc(canonical)}">`}<meta property="og:image" content="${absolute(image?.src||photoOutside)}"><link rel="icon" href="${logo}" type="image/webp"><link rel="stylesheet" href="/assets/site.css">${schemaTags}${analytics}</head><body>${headerMarkup}<main id="main">${hero}${content}</main>${footer}<script src="/assets/site.js" defer></script></body></html>`;
}
function section(title,intro,body,cls='section') { return `<section class="${cls}"><div class="wrap"><div class="section-head"><p class="eyebrow">DOST TEKNİK <span>·</span> BODRUM</p><h2>${title}</h2>${intro?`<p>${intro}</p>`:''}</div>${body}</div></section>`; }
function faqSection(items) { return section('Sık sorulan sorular','Servis talebinden önce merak ettiklerinize kısa yanıtlar.',`<div class="faq-list">${items.map(([q,a])=>faq(q,a)).join('')}</div>`,'section section-faq'); }
function contactActions(message='Merhaba, servis talebi oluşturmak istiyorum.') { return `<div class="actions"><a class="button" href="${phoneLink}">${icon('phone')} Hemen ara · ${site.phone}</a><a class="button button-whatsapp" href="${whatsappFor(message)}" rel="noopener">${icon('chat')} WhatsApp ile yaz</a></div>`; }
function serviceFaqs(item) { return serviceDetails[item.slug].faq; }
function regionFaqs(region) { return [[`${region.name} bölgesinde klima servisi için nasıl ulaşabilirim?`,`Dost Teknik’e telefonla veya WhatsApp’tan ulaşıp cihaz türü, belirti ve ${region.name} konum bilgisini iletin.`],['Hangi cihazlar için servis talebi alınıyor?','Klima ve ev tipi beyaz eşya servis başlıklarını hizmetler sayfasından inceleyebilirsiniz.']]; }
function brandFaqs(brandName) { return [[`${brandName} için servis talebinde hangi bilgileri paylaşmalıyım?`,'Cihazın model etiketindeki bilgileri, ürün türünü ve arıza belirtisini paylaşmanız ilk değerlendirmeye yardımcı olur.'],['Dost Teknik üretici yetkili servisi midir?','Dost Teknik bağımsız teknik servis hizmeti sunar; üretici yetkili servisi olduğu iddiasında bulunmaz.']]; }
function faqStructured(items) { return [faqSchema(items)]; }
function commonCTA(label='Servis ihtiyacınız mı var?',message='Merhaba, servis talebi oluşturmak istiyorum.') { return section(label,'Cihazın türünü, bulunduğunuz mahalleyi ve yaşadığınız belirtiyi paylaşın. Servis kapsamını birlikte netleştirelim.',`<div class="cta-panel"><div><p class="eyebrow">DOĞRUDAN İLETİŞİM</p><h3>Servis talebinizi Dost Teknik’e iletin</h3><p>Telefonla arayın veya WhatsApp’tan cihaz bilgilerini gönderin.</p></div>${contactActions(message)}</div>`,'section section-cta'); }
function localLinks(current=null) { return regions.filter(r=>r.slug!==current).map(r=>r); }
function guideLinks(slugs) { return `<div class="context-links">${slugs.map(slug=>enrichedGuides.find(g=>g.slug===slug)).filter(Boolean).map(g=>`<a href="${g.url}"><span class="context-link-topic">${esc(g.category)}</span><strong>${esc(g.title)}</strong><small>${esc(g.description)}</small>${icon('arrow')}</a>`).join('')}</div>`; }
function requestChecklist(items) { return `<ul class="request-checklist">${items.map(item=>`<li>${esc(item)}</li>`).join('')}</ul>`; }
function serviceStepList(items) { return `<ol class="service-intent-list">${items.map((item,i)=>`<li><span>${String(i+1).padStart(2,'0')}</span>${esc(item)}</li>`).join('')}</ol>`; }
function serviceSchema(item) { return {'@context':'https://schema.org','@type':'Service','name':item.name,'serviceType':item.name,'provider':{'@type':'HVACBusiness','name':site.name,'telephone':site.phone},'areaServed':{'@type':'AdministrativeArea','name':'Bodrum Yarımadası'}}; }
function writePage(path,html) { const relative=path==='/'?'index.html':path.replace(/^\//,''); const target=join(out,relative.endsWith('/')?`${relative}index.html`:relative); return mkdir(dirname(target),{recursive:true}).then(()=>writeFile(target,html)); }

await rm(out,{recursive:true,force:true});
await mkdir(join(out,'assets/images'),{recursive:true});
await mkdir(join(out,'assets'),{recursive:true});
for (const f of ['dost-teknik-logo.webp','dost-teknik-isletme-dis.webp','dost-teknik-isletme-ici.webp']) await copyFile(join(root,'assets/images',f),join(out,'assets/images',f));
const css = await readFile(join(root,'assets/site.css'),'utf8'); await writeFile(join(out,'assets/site.css'),css);
const js = await readFile(join(root,'assets/site.js'),'utf8'); await writeFile(join(out,'assets/site.js'),js);

const trustItems = [
  ['pin','Yerel merkez','Akçaalan, Turgutreis'],['snow','Klima servisi','Bakım ve onarım'],
  ['appliance','Beyaz eşya','Ev tipi cihaz desteği'],['clock','Çalışma saati',site.hours]
];
const processSteps = [['01','Servis talebi','Telefon veya WhatsApp’tan bize ulaşın.'],['02','Cihaz bilgisi','Ürün türünü, marka-modeli ve belirtiyi paylaşın.'],['03','Teknik değerlendirme','Sorunu ve uygun servis kapsamını birlikte netleştirelim.'],['04','Servis süreci','Uygunluk ve işlem planı için sizinle iletişim kuralım.']];
const homeFaqs = [
 ['Hangi bölgelerde servis talebi oluşturabilirim?','Dost Teknik, Turgutreis merkezli olarak Bodrum Yarımadası genelindeki klima ve beyaz eşya servis taleplerini değerlendirir.'],
 ['Servis kaydı için hangi bilgileri paylaşmalıyım?','Cihaz türü, marka-model, arıza belirtisi ve bulunduğunuz mahalle ilk değerlendirmeye yardımcı olur.'],
 ['WhatsApp ile ulaşabilir miyim?','Evet. Sitedeki WhatsApp bağlantısı 0534 889 51 48 numarasına yönlenir.']
];
const featuredAreas = ['turgutreis','akyarlar','islamhaneleri','gumusluk','ortakent','bitez','yalikavak','gumbet'].map(slug=>regions.find(r=>r.slug===slug));
const featuredBrands = ['arcelik','beko','bosch','siemens','vestel','daikin','samsung','lg','hantech','mitsubishi-electric'].map(slug=>brands.find(b=>b.slug===slug));
const homeContent =
  `<section class="trust-strip" aria-label="Dost Teknik hizmet bilgileri"><div class="wrap trust-grid">${trustItems.map(([name,title,body])=>`<div class="trust-item"><span class="trust-icon">${icon(name)}</span><span><strong>${title}</strong><small>${body}</small></span></div>`).join('')}</div></section>` +
  section('Servis ihtiyacınıza uygun destek','Klima ve ev tipi cihazlar için ayrı servis başlıklarını inceleyin.',`${serviceCards(services.slice(0,6))}<div class="section-link">${link('/hizmetler/','Tüm hizmetleri görüntüle','text-link')}</div>`) +
  section('Yerel işletme. Doğrudan iletişim.','Dost Teknik’in gerçek işletme alanını ve adresini görün.',`<div class="editorial-grid"><div class="editorial-copy"><p class="eyebrow">DOST TEKNİK · AKÇAALAN</p><h3>Turgutreis’ten Bodrum Yarımadası’na</h3><p>İşletmemiz Akçaalan Mahallesi Zübeyde Hanım Caddesi’ndedir. Servis talebinizi doğrudan bize iletin; cihaz ve arıza bilgilerini birlikte değerlendirelim.</p><p class="address-line">${icon('pin')} ${site.address}</p>${link('/hakkimizda.html','İşletmemizi tanıyın','text-link')}</div><div class="photo-stack"><img class="editorial-main" src="${photoInside}" width="1200" height="1600" loading="lazy" alt="Dost Teknik işletme iç mekânında klima ürünlerinin sergilendiği alan"><div class="editorial-note"><span class="caption-mark">D</span><span><strong>Dost Teknik</strong><small>Klima &amp; beyaz eşya servisi</small></span></div></div></div>`) +
  section('Servis süreci nasıl ilerler?','İlk görüşmeden servis planına kadar temel adımlar.',`<ol class="process-grid">${processSteps.map(([num,title,body])=>`<li class="process-step"><span class="process-number">${num}</span><h3>${title}</h3><p>${body}</p></li>`).join('')}</ol>`) +
  section('Servis verdiğimiz markalar','Marka sayfalarında cihaz grupları ve hizmet bölgeleri hakkında bilgi alın.',`<div class="brand-chips">${featuredBrands.map(b=>link(b.url,b.name,'brand-chip')).join('')}</div><div class="section-link">${link('/markalar/','60 markanın tamamını görüntüle','text-link')}</div>`) +
  section('Bodrum Yarımadası genelinde','Öne çıkan hizmet bölgelerini görün; tüm bölgeler ayrı sayfalarda listelenmiştir.',`<div class="area-grid">${featuredAreas.map((r,i)=>`<a class="area-card${i===0?' area-card-main':''}" href="${r.url}"><span class="area-count">${String(i+1).padStart(2,'0')}</span><strong>${r.name}</strong>${icon('arrow')}</a>`).join('')}</div><div class="section-link">${link('/bolgeler/','Tüm hizmet bölgelerini görüntüle','text-link')}</div>`) +
  section('Bilgi merkezi','Klima ve ev tipi cihazlarla ilgili pratik rehberleri inceleyin.',`<div class="guide-grid">${guides.slice(0,3).map(g=>`<a class="guide-card" href="${g.url}"><span class="guide-label">TEKNİK REHBER</span><h3>${g.title}</h3><p>${g.description}</p><span class="text-link">Rehberi oku ${icon('arrow')}</span></a>`).join('')}</div><div class="section-link">${link('/bilgi-merkezi/','Tüm rehberlere git','text-link')}</div>`) +
  faqSection(homeFaqs) + commonCTA();
await writePage('/',render({path:'/',title:'Turgutreis Klima Servisi ve Bodrum Beyaz Eşya | Dost Teknik',description:'Dost Teknik; Turgutreis merkezli klima bakım, onarım ve beyaz eşya servis desteğiyle Bodrum Yarımadası genelinde hizmet verir.',h1:'Turgutreis Klima Servisi · Bodrum’da Teknik Destek',content:homeContent,image:{src:photoOutside,width:1086,height:1448,alt:'Dost Teknik klima ve beyaz eşya servis işletmesinin dış görünümü',eager:true},isHome:true,schemas:[faqSchema(homeFaqs)]}));

const directoryPages = [
 {path:'/hizmetler/',name:'Hizmetler',title:'Klima ve Beyaz Eşya Hizmetleri | Dost Teknik',desc:'Klima tamiri, bakım, montaj ve Bodrum’da beyaz eşya servis hizmetlerini inceleyin.',items:services,type:'services'},
 {path:'/bolgeler/',name:'Hizmet Bölgeleri',title:'Bodrum Klima Servisi Bölgeleri | Dost Teknik',desc:'Turgutreis merkezli hizmet verdiğimiz Bodrum Yarımadası mahalle ve bölgelerini inceleyin.',items:regions,type:'regions'},
 {path:'/markalar/',name:'Markalar',title:'Klima ve Beyaz Eşya Markaları | Dost Teknik',desc:'Dost Teknik’in klima ve beyaz eşya servis kapsamındaki marka sayfalarını inceleyin.',items:brands,type:'brands'},
 {path:'/bilgi-merkezi/',name:'Bilgi Merkezi',title:'Klima ve Beyaz Eşya Rehberleri | Dost Teknik',desc:'Klima ve ev tipi cihazların bakımı, arıza belirtileri ve servis hazırlığı hakkında rehberler.',items:enrichedGuides,type:'guides'}
];
for (const d of directoryPages) {
 const bodyContent=d.type==='services'?`<div class="directory-topic"><h2>Klima sistemleri</h2><p>Klima bakım, arıza ve kurulum başlıkları.</p>${serviceCards(d.items.filter(x=>['klima-tamiri','klima-bakimi','klima-montaji','klima-gaz-dolumu','klima-temizligi','klima-kart-tamiri','vrf-vrv-servisi','multi-split-klima-servisi'].includes(x.slug)))}</div><div class="directory-topic"><h2>Beyaz eşya</h2><p>Cihaz türüne göre servis başlıkları.</p>${serviceCards(d.items.filter(x=>!['klima-tamiri','klima-bakimi','klima-montaji','klima-gaz-dolumu','klima-temizligi','klima-kart-tamiri','vrf-vrv-servisi','multi-split-klima-servisi'].includes(x.slug)))}</div>`
  :d.type==='regions'?`<div class="featured-region"><div><span class="guide-label">YEREL MERKEZ</span><h2>Turgutreis ve Bodrum Yarımadası</h2><p>Dost Teknik Akçaalan’daki işletmesinden bölge genelindeki servis taleplerini değerlendirir.</p></div>${link(d.items.find(x=>x.slug==='turgutreis').url,'Turgutreis sayfasını incele','text-link')}</div><h2 class="directory-subhead">Tüm hizmet bölgeleri</h2><div class="area-grid">${[...d.items].sort((a,b)=>a.name.localeCompare(b.name,'tr')).map(r=>`<a class="area-card${r.slug==='turgutreis'?' area-card-main':''}" href="${r.url}"><span class="area-count">${r.slug==='turgutreis'?'YEREL MERKEZ':'HİZMET BÖLGESİ'}</span><strong>${esc(r.name)}</strong>${icon('arrow')}</a>`).join('')}</div>`
  :d.type==='brands'?(()=>{const sorted=[...d.items].sort((a,b)=>a.name.localeCompare(b.name,'tr'));const grouped=Map.groupBy?Map.groupBy(sorted,b=>b.name.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ı/g,'i')[0].toLocaleUpperCase('tr')):sorted.reduce((m,b)=>{const k=b.name.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ı/g,'i')[0].toLocaleUpperCase('tr');m.set(k,[...(m.get(k)||[]),b]);return m},new Map());const entries=grouped instanceof Map?[...grouped]:[...grouped.entries()];return `<div class="directory-search-wrap"><label class="directory-search"><span>Marka ara</span><input type="search" id="brand-search" placeholder="Örn. Arçelik, Bosch" autocomplete="off" aria-controls="brand-directory"></label><p id="brand-search-count" aria-live="polite">${sorted.length} marka</p></div><nav class="alphabet-nav" aria-label="Marka harfleri">${entries.map(([letter])=>link(`#brand-letter-${letter}`,letter)).join('')}</nav><div id="brand-directory">${entries.map(([letter,items])=>`<section class="brand-group" id="brand-letter-${letter}"><h2>${esc(letter)}</h2><div class="brand-chips">${items.map(b=>`<a class="brand-chip" href="${b.url}" data-brand-name="${esc(b.name)}">${esc(b.name)}</a>`).join('')}</div></section>`).join('')}</div>`})()
  :[...new Set(d.items.map(g=>g.category))].map(category=>`<section class="guide-topic-group"><h2>${esc(category)}</h2><div class="guide-grid guide-grid-directory">${d.items.filter(g=>g.category===category).map(g=>`<a class="guide-card" href="${g.url}"><span class="guide-label">${esc(category.toLocaleUpperCase('tr'))}</span><h3>${esc(g.title)}</h3><p>${esc(g.description)}</p><span class="text-link">Rehberi oku ${icon('arrow')}</span></a>`).join('')}</div></section>`).join('');
 const body=section(d.name, d.desc, bodyContent);
 await writePage(d.path,render({path:d.path,title:d.title,description:d.desc,h1:d.name,crumbs:[{name:d.name,url:d.path}],content:body}));
}

for (const item of services) {
 const desc=`${item.description} Turgutreis ve Bodrum’da servis talebi için Dost Teknik’e ulaşın.`;
 const detail=serviceDetails[item.slug], questions=serviceFaqs(item);
 const related=serviceRelatedMap[item.slug].map(slug=>services.find(x=>x.slug===slug));
 const guidesForService=detail.guideSlugs;
 const message=`Merhaba, ${item.name} için servis talebi oluşturmak istiyorum. Cihaz türü/modeli: __. Belirti: __. Bulunduğum bölge: __.`;
 const text=section('Hangi durumlarda bu hizmet için ulaşabilirsiniz?',item.description,serviceStepList(detail.requestCases),'section section-open') + section('İlk görüşme için hazırlayabilecekleriniz','Marka ve model etiketini cihazı sökmeden, erişilebilir durumdaysa not edin.',requestChecklist(detail.beforeContact),'section section-tint') + section('Konuya uygun teknik rehberler','Belirti ve bakım hakkında kullanıcıya yönelik açıklamalar.',guideLinks(guidesForService),'section section-open') + section('Yakın hizmet başlıkları','İhtiyaç klima veya ev cihazının başka bir işleviyle ilişkiliyse ilgili kapsamı seçin.',serviceCards(related)) + faqSection(questions) + commonCTA(`${item.name} için servis talebi`,message);
 await writePage(item.url,render({path:item.url,title:`${item.name} Turgutreis | Dost Teknik`,description:desc,h1:`Turgutreis ${item.name}`,crumbs:[{name:'Hizmetler',url:'/hizmetler/'},{name:item.name,url:item.url}],content:text,schemas:[serviceSchema(item),...faqStructured(questions)],whatsappMessage:message}));
}

for (const region of regions) {
 const desc=`${region.name} bölgesinde klima ve beyaz eşya servis talebi için Dost Teknik’e ulaşın. Cihaz ve arıza bilgileriyle ilk değerlendirmeyi başlatın.`;
 const combos=brandRegionPairs.filter(p=>p.region.slug===region.slug).map(p=>({name:`${p.brand.name} servisi`,url:`/servis/${region.slug}/${p.brand.slug}-servisi.html`}));
  const questions=regionFaqs(region);
  const message=`Merhaba, ${region.name} bölgesindeki servis talebim için yazıyorum. Cihaz türü/modeli: __. Belirti: __.`;
  const regionGuides=['servis-cagirirken-hangi-bilgiler','klima-bakimi-ne-zaman-yapilmali','buzdolabi-sogutmuyor'];
  const regionalServices=['klima-tamiri','klima-bakimi','beyaz-esya-tamiri','buzdolabi-servisi','camasir-makinesi-servisi','bulasik-makinesi-servisi','kurutma-makinesi-servisi','ankastre-servisi'].map(slug=>services.find(s=>s.slug===slug));
  const content=section(`${region.name} bölgesinde servis talebi`, `Dost Teknik Akçaalan’daki işletmesinden Bodrum Yarımadası genelindeki talepleri değerlendirir. ${region.name} konum bilgisini cihazın türü ve belirtisiyle birlikte iletin.`, `<div class="location-intro"><span class="location-intro-icon">${icon('pin')}</span><div><strong>${esc(region.name)} · Bodrum Yarımadası</strong><p>Uygunluk ve işlem kapsamı servis talebi sırasında netleştirilir. Sayfa, bu bölgedeki kullanıcıların hizmet başlıklarına ve iletişim bilgilerine hızlı erişmesi için hazırlanmıştır.</p></div></div>`) + section('Hangi cihazlar için destek var?','Önce cihaz türünü seçin; her hizmet sayfasında talep öncesi gerekli bilgiler yer alır.',serviceCards(regionalServices)) + (combos.length?section(`${region.name} için kaynakta bağlantısı bulunan marka sayfaları`,'Bu bağlantılar erişilebilir referans sayfalarında görülen eşleşmelerdir.',cards(combos)): '') + section('Servis talebi öncesinde','Telefon veya WhatsApp görüşmesi için cihaz ve arıza bilgisini hazırlayın.',requestChecklist(['Cihaz türü ve model etiketi','Gözlenen belirti ve başlangıç zamanı','Varsa ekrandaki hata kodu','Bulunduğunuz mahalle veya konum'])) + section('İlgili rehberler','Servis kaydı ve cihaz belirtileri hakkında kısa bilgi.',guideLinks(regionGuides),'section section-open') + section('Diğer hizmet bölgeleri','Bodrum Yarımadası’ndaki diğer hizmet alanlarını inceleyin.',cards(localLinks(region.slug).slice(0,8))) + faqSection(questions) + commonCTA(`${region.name} için servis talebi`,message);
  await writePage(region.url,render({path:region.url,title:`${region.name} Klima Servisi & Beyaz Eşya | Dost Teknik`,description:desc,h1:`${region.name} Klima Servisi & Beyaz Eşya Tamiri`,crumbs:[{name:'Hizmet Bölgeleri',url:'/bolgeler/'},{name:region.name,url:region.url}],content,image:region.slug==='turgutreis'?{src:photoOutside,width:1086,height:1448,alt:'Dost Teknik Bodrum klima servis işletmesi dış görünümü'}:null,schemas:faqStructured(questions),whatsappMessage:message}));
}

for (const brand of brands) {
 const desc=`${brand.name} marka cihazınızın türü, modeli ve arıza belirtisiyle Bodrum bölgesinde bağımsız servis talebinizi Dost Teknik’e iletin.`;
 const linked=linkedRegionSlugs.map(s=>regions.find(r=>r.slug===s));
  const questions=brandFaqs(brand.name);
  const message=`Merhaba, ${brand.name} marka cihazım için servis talebi oluşturmak istiyorum. Cihaz türü/modeli: __. Belirti: __. Bulunduğum bölge: __.`;
  const content=section(`${brand.name} marka cihaz için servis talebi`,`Bu marka adı üretici veya yetkili servis bağlantısı anlamına gelmez. Dost Teknik bağımsız teknik servis hizmeti sunar.`, `<div class="prose"><p>${esc(brand.name)} cihazınızın türünü, model etiketini ve arıza belirtisini paylaşın. Marka sayfasında cihaz türü veya model kapsamına ilişkin doğrulanmamış bir yetki iddiası yer almaz; işlem ve parça uygunluğu cihaz incelendikten sonra belirlenir.</p><h3>İlk değerlendirme için</h3>${requestChecklist(['Cihaz türü ve erişilebilir model etiketi','Varsa hata kodu veya uyarı ışığı','Belirtinin ne zaman ve hangi kullanımda başladığı','Bulunduğunuz hizmet bölgesi'])}<p>Kullanım güvenli değilse cihazı çalıştırmaya devam etmeyin ve telefonla önce durumu aktarın.</p></div>`) + section('Cihaz türünü seçin','Hizmet başlıkları marka sayfasından bağımsız olarak cihaz türüne göre düzenlenmiştir.',serviceCards([services.find(s=>s.slug==='klima-tamiri'),services.find(s=>s.slug==='beyaz-esya-tamiri')])) + section('Servis hazırlığı hakkında rehber','Model, belirti ve bölge bilgisini nasıl ileteceğinizi öğrenin.',guideLinks(['servis-cagirirken-hangi-bilgiler','klima-neden-sogutmaz','buzdolabi-sogutmuyor']),'section section-open') + section(`${brand.name} sayfasında doğrulanan hizmet bölgeleri`,'Aşağıdaki bölgeler kaynak marka sayfasında bağlantı olarak yer almaktadır.',cards(linked)) + faqSection(questions) + commonCTA(`${brand.name} cihazınız için servis talebi`,message);
  const brandTitle=`${brand.name} Servisi Turgutreis & Bodrum | Dost Teknik`;
  await writePage(brand.url,render({path:brand.url,title:brandTitle.length>65?`${brand.name} Servisi | Dost Teknik`:brandTitle,description:desc,h1:`Turgutreis ${brand.name} Klima & Beyaz Eşya Servisi`,crumbs:[{name:'Markalar',url:'/markalar/'},{name:brand.name,url:brand.url}],content,schemas:faqStructured(questions),whatsappMessage:message}));
}

for (const pair of brandRegionPairs) {
 const path=`/servis/${pair.region.slug}/${pair.brand.slug}-servisi.html`;
 const desc=`${pair.brand.name} cihaz için ${pair.region.name} bölgesindeki servis talebinizi model ve belirtiyle Dost Teknik’e iletin. Bağımsız değerlendirme isteyin.`;
 const message=`Merhaba, ${pair.region.name} bölgesinde ${pair.brand.name} marka cihazım için servis talebi oluşturmak istiyorum. Cihaz türü/modeli: __. Belirti: __.`;
 const sourceNote=pair.verifiedFrom==='region'?`Bu adres, ${pair.region.name} hizmet bölgesi sayfasında görülen marka bağlantısına karşılık gelir.`:`Bu adres, ${pair.brand.name} marka sayfasında görülen bölge bağlantısına karşılık gelir.`;
 const content=section('Talep öncesinde hazırlayın',`Cihaz türü ve marka-model bilgisini ${pair.region.name} konum bilgisiyle birlikte iletin.`, `<div class="matrix-intro"><p>${esc(pair.region.name)} bölgesindeki ${esc(pair.brand.name)} marka cihazınız için ilk değerlendirme; cihaz türü, model ve belirtilere göre yapılır. ${esc(sourceNote)} Marka adı üretici yetkili servis bağlantısı anlamına gelmez.</p><p><strong>Dost Teknik bağımsız teknik servis hizmeti sunar.</strong> Cihaz ve parça kapsamı inceleme sonrasında netleştirilir.</p></div>${requestChecklist(['Cihaz türü ve marka-model etiketi','Arıza belirtisi ve başlangıç zamanı','Varsa hata kodu veya uyarı ışığı',`${pair.region.name} bölgesindeki konumunuz`])}`) + section('Servis değerlendirmesi nasıl ilerler?','Başvuruda paylaşılan bilgiler uygun yönlendirmeyi destekler.',`<ol class="process-grid process-grid-compact">${processSteps.map(([num,title,body])=>`<li class="process-step"><span class="process-number">${num}</span><h3>${title}</h3><p>${body}</p></li>`).join('')}</ol>`) + section('Cihaz türüne göre hizmet seçin','Marka ve model bilgisiyle birlikte ihtiyacınız olan cihaz grubunu belirtin.',serviceCards([services.find(s=>s.slug==='klima-tamiri'),services.find(s=>s.slug==='beyaz-esya-tamiri')])) + section('Marka ve bölge bilgileri','Cihaz ve konumla ilgili diğer sayfalara geçin.',cards([{name:`${pair.brand.name} marka bilgisi`,url:pair.brand.url},{name:`${pair.region.name} hizmet bölgesi`,url:pair.region.url}])) + section('Servis kaydı için kısa rehber','Model, belirti, hata kodu ve konum bilgisini hazırlama.',guideLinks(['servis-cagirirken-hangi-bilgiler']),'section section-open') + section('Marka sayfasında bağlantısı görülen diğer bölgeler','Bu bağlantılar kaynak marka sayfasında doğrulanmıştır.',cards(linkedRegionSlugs.filter(s=>s!==pair.region.slug).slice(0,6).map(s=>regions.find(r=>r.slug===s)))) + commonCTA(`${pair.region.name} ${pair.brand.name} servis talebi`,message);
 await writePage(path,render({path,title:`${pair.region.name} ${pair.brand.name} Servisi | Dost Teknik`,description:desc,h1:`${pair.region.name} ${pair.brand.name} Servisi`,crumbs:[{name:'Markalar',url:'/markalar/'},{name:pair.brand.name,url:pair.brand.url},{name:pair.region.name,url:pair.region.url}],content,whatsappMessage:message}));
}

for (const guide of enrichedGuides) {
 const desc=guide.description;
 const relatedGuideLinks=guide.related.map(g=>g.slug);
 const article=`<div class="guide-answer"><span class="guide-answer-mark">Kısa yanıt</span><p>${esc(guide.answer)}</p></div><div class="guide-columns"><section class="guide-topic-panel"><h3>${esc(guide.diagnosticHeading)}</h3><ul class="guide-list">${guide.observations.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></section><section class="guide-topic-panel guide-topic-panel-safe"><h3>${esc(guide.safeHeading)}</h3><ul class="guide-list">${guide.safeChecks.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></section></div><section class="guide-callout"><h3>Ne zaman teknik servis gerekir?</h3><p>${esc(guide.serviceTrigger)}</p><h4>Servis talebinde bu bilgiyi paylaşın</h4><p>${esc(guide.tellService)}</p></section>`;
 const content=section(guide.diagnosticHeading,guide.answer,article,'section section-open') + section('Bu konuyla ilgili hizmetler','Cihaz türüne uygun servis başlığını seçin.',serviceCards(guide.serviceSlugs.map(slug=>services.find(s=>s.slug===slug)).filter(Boolean))) + section('Bağlantılı rehberler','Aynı cihaz veya belirti kümesindeki diğer açıklamalar.',guideLinks(relatedGuideLinks),'section section-open') + commonCTA(`“${guide.title}” hakkında servis desteği` ,`Merhaba, “${guide.title}” konusu hakkında servis desteği almak istiyorum. Cihaz türü/modeli: __. Belirti: __. Bulunduğum bölge: __.`);
 await writePage(guide.url,render({path:guide.url,title:guide.metaTitle||`${guide.title} | Dost Teknik`,description:desc,h1:guide.title,crumbs:[{name:'Bilgi Merkezi',url:'/bilgi-merkezi/'},{name:guide.title,url:guide.url}],content,whatsappMessage:`Merhaba, “${guide.title}” konusu hakkında servis desteği almak istiyorum. Cihaz türü/modeli: __. Belirti: __. Bulunduğum bölge: __.`}));
}

const aboutPath='/hakkimizda.html', contactPath='/iletisim.html';
await writePage(aboutPath,render({path:aboutPath,title:'Dost Teknik Hakkında | Turgutreis, Bodrum',description:'Dost Teknik’in Bodrum Akçaalan’daki işletmesi, klima ve ev tipi cihaz servis kapsamı ve iletişim yaklaşımı hakkında bilgi alın.',h1:'Turgutreis Merkezli Klima & Beyaz Eşya Teknik Servis',crumbs:[{name:'Hakkımızda',url:aboutPath}],content:section('Akçaalan’daki işletmemiz','Dost Teknik, Turgutreis’teki işletme adresinden Bodrum Yarımadası genelindeki klima ve beyaz eşya servis taleplerini değerlendirir.',`<div class="split"><img src="${photoInside}" width="1200" height="1600" loading="lazy" alt="Dost Teknik işletmesinde sergilenen klima üniteleri"><div class="prose"><h3>Servis talebinden önce</h3><p>Cihaz türünü, modelini ve gözlemlediğiniz belirtiyi telefonla veya WhatsApp’tan paylaşın. Uygun servis kapsamı ve işlem planı teknik değerlendirme sonrasında netleştirilir.</p><h3>Bağımsız teknik servis</h3><p>Dost Teknik üretici yetkili servisi olduğunu iddia etmez. Marka adı, tek başına üreticiyle yetkili servis bağlantısı anlamına gelmez.</p><h3>İşletme adresi</h3><address>${site.address}</address></div></div>`) + section('Servis başlıkları','Klima ve ev tipi cihazlar için kapsamı inceleyin.',serviceCards(['klima-tamiri','klima-bakimi','beyaz-esya-tamiri','buzdolabi-servisi','camasir-makinesi-servisi','bulasik-makinesi-servisi','kurutma-makinesi-servisi','ankastre-servisi'].map(slug=>services.find(s=>s.slug===slug)))) + section('Bölge sayfaları','Turgutreis merkezli hizmet talebi için bulunduğunuz bölgeyi seçin.',cards(featuredAreas)) + commonCTA()}));
const contactMessage='Merhaba, Dost Teknik’ten servis talebi oluşturmak istiyorum. Cihaz türü/modeli: __. Arıza belirtisi: __. Bulunduğum bölge: __.';
await writePage(contactPath,render({path:contactPath,title:'Dost Teknik İletişim ve Servis Kaydı | Bodrum',description:`Dost Teknik’e ${site.phone} numarasından ulaşın. Adres: ${site.address}. Çalışma saatleri ${site.hours}.`,h1:'Turgutreis Klima & Beyaz Eşya Servis Kaydı',crumbs:[{name:'İletişim',url:contactPath}],content:section('Servis talebinizi iletin','Telefonla arayın ya da WhatsApp mesajında cihaz ve arıza bilgisini paylaşın.',`<div class="contact-grid"><div class="contact-details"><div class="contact-method"><span>${icon('phone')}</span><div><h3>Telefon</h3><a class="contact-phone" href="${phoneLink}">${site.phone}</a></div></div><div class="contact-method"><span>${icon('chat')}</span><div><h3>WhatsApp</h3><a href="${whatsappFor(contactMessage)}" rel="noopener">Hazır servis mesajı oluştur</a></div></div><div class="contact-method"><span>${icon('pin')}</span><div><h3>İşletme adresi</h3><address>${site.address}</address></div></div><div class="contact-method"><span>${icon('clock')}</span><div><h3>Çalışma saatleri</h3><p>${site.hours}</p></div></div><p class="contact-instagram">Instagram · ${site.instagram}</p>${site.mapsUrl?`<p><a href="${esc(site.mapsUrl)}" rel="noopener">Haritada görüntüle</a></p>`:''}</div><img src="${photoOutside}" width="1086" height="1448" loading="lazy" alt="Dost Teknik’in Akçaalan’daki işletme dış görünümü"></div>`) + section('Mesajdan önce hazırlayabilecekleriniz','Bu bilgiler ilk görüşmede cihazı ve talebi tanımlamaya yardımcı olur.',requestChecklist(['Cihaz türü ve model etiketi','Arıza belirtisi ve varsa hata kodu','Sorunun başlangıç zamanı','Bulunduğunuz bölge'])) + section('İlk görüşmede nasıl ilerler?','Cihaz bilgisini ve bölgenizi paylaştığınızda servis kapsamı birlikte değerlendirilir.',serviceStepList(['Talebinizi telefonla veya WhatsApp’tan iletin.','Cihazın modelini, belirtisini ve varsa hata kodunu paylaşın.','Uygunluk ve işlem kapsamı hakkında bilgi alın.'])) + section('Hizmet bölgeleri','Bodrum Yarımadası’nda servis talebinizi bulunduğunuz bölgeyle birlikte iletin. Görüşmede uygunluk ve planlama bilgisini teyit edin.',cards(featuredAreas)),whatsappMessage:contactMessage}));

const sitemapUrls=[...new Set(knownUrls)];
const sitemap=`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${sitemapUrls.map(p=>`  <url><loc>${esc(absolute(p))}</loc></url>`).join('\n')}\n</urlset>\n`;
await writeFile(join(out,'sitemap.xml'),sitemap);
await writeFile(join(out,'robots.txt'),`User-agent: *\nAllow: /\nSitemap: ${absolute('/sitemap.xml')}\n`);
await writeFile(join(out,'404.html'),render({path:'/404.html',title:'Sayfa Bulunamadı | Dost Teknik',description:'Aradığınız sayfa bulunamadı. Dost Teknik ana sayfasına veya hizmet bölgelerine geçin.',h1:'Bu sayfayı bulamadık',content:section('Aradığınız sayfa mevcut değil','Adres değişmiş veya kaldırılmış olabilir.',`<div class="actions">${link('/','Ana sayfaya dön','button')}${link('/hizmetler/','Hizmetleri incele','button secondary')}${link('/bolgeler/','Bölgeleri görüntüle','button secondary')}</div>`)}));
await writeFile(join(out,'.nojekyll'),'');
console.log(`Build complete: ${sitemapUrls.length} indexable URLs; ${brandRegionPairs.length} verified brand/region pages.`);
