export const site = {
  name: 'Dost Teknik',
  phone: '+90 534 889 51 48',
  get phoneDigits(){ return this.phone.replace(/\D/g,''); },
  addressParts: { streetAddress: 'Akçaalan Mahallesi Zübeyde Hanım Caddesi No:30/2', addressLocality: 'Bodrum', addressRegion: 'Muğla', addressCountry: 'TR' },
  get address(){ return `${this.addressParts.streetAddress}, ${this.addressParts.addressLocality}/${this.addressParts.addressRegion}`; },
  hours: '09:00–20:00',
  instagram: '@teknik.dost',
  siteUrl: 'https://example.com',
  mapsUrl: '', businessProfileUrl: '', latitude: '', longitude: '', analyticsId: ''
};

export const services = [
 ['Klima Tamiri','klima-tamiri','Klima arızalarının belirtilerini değerlendirip onarım seçeneklerini açıklıyoruz.'],
 ['Klima Bakımı','klima-bakimi','Mevsim geçişlerinde filtre, drenaj ve çalışma kontrolleriyle klimanızın bakımını planlıyoruz.'],
 ['Klima Montajı & Demontajı','klima-montaji','Klima montajı, sökümü ve yeniden kurulumunda mekâna uygun teknik planlama yapıyoruz.'],
 ['Klima Gaz Kontrolü & Dolumu','klima-gaz-dolumu','Soğutma performansını ve sistem koşullarını kontrol ederek gaz işlemi gereksinimini belirliyoruz.'],
 ['Klima Temizliği','klima-temizligi','İç ünite filtreleri ve erişilebilir bileşenler için cihaz tipine uygun temizlik desteği sağlıyoruz.'],
 ['Klima Elektronik Kart Kontrolü','klima-kart-tamiri','Elektronik kart ve bağlantı kaynaklı çalışma sorunlarını arıza tespitiyle inceliyoruz.'],
 ['VRF / VRV Klima Servisi','vrf-vrv-servisi','VRF ve VRV sistemlerinde çalışma, kontrol ve periyodik bakım ihtiyaçlarını değerlendiriyoruz.'],
 ['Multi Split Klima Servisi','multi-split-klima-servisi','Birden fazla iç üniteli multi split sistemlerde ünite ve bağlantı kontrolleri yapıyoruz.'],
 ['Beyaz Eşya Tamiri','beyaz-esya-tamiri','Ev tipi beyaz eşyalarda arıza tespiti ve onarım için servis desteği sunuyoruz.'],
 ['Buzdolabı Servisi','buzdolabi-servisi','Soğutmama, ses ve çalışma sorunlarında buzdolabı kontrolleri gerçekleştiriyoruz.'],
 ['Çamaşır Makinesi Servisi','camasir-makinesi-servisi','Su alma, boşaltma ve sıkma sorunları için çamaşır makinesi servisi sağlıyoruz.'],
 ['Bulaşık Makinesi Servisi','bulasik-makinesi-servisi','Yıkama, su alma ve tahliye belirtilerini inceleyerek bulaşık makinesi desteği veriyoruz.'],
 ['Kurutma Makinesi Servisi','kurutma-makinesi-servisi','Kurutma performansı ve hava dolaşımıyla ilgili belirtileri kontrol ediyoruz.'],
 ['Derin Dondurucu Servisi','derin-dondurucu-servisi','Soğutma ve çalışma sorunlarında derin dondurucu arıza tespiti yapıyoruz.'],
 ['Ankastre Cihaz Servisi','ankastre-servisi','Mutfak ankastre cihazlarında belirtilere ve cihaz modeline uygun servis desteği sunuyoruz.']
].map(([name,slug,description])=>({name,slug,url:`/hizmetler/${slug}.html`,description}));

export const regions = [
 ['Turgutreis','turgutreis'],['Akçaalan','akcaalan'],['Bahçelievler','bahcelievler'],['Karabağ','karabag'],['İslamhaneleri','islamhaneleri'],['Akyarlar','akyarlar'],['Karaincir','karaincir'],['Bağla','bagla'],['Gümüşlük','gumusluk'],['Gümüşkaya','gumuskaya'],['Koyunbaba','koyunbaba'],['Ortakent','ortakent'],['Yahşi','yahsi'],['Bitez','bitez'],['Gümbet','gumbet'],['Konacık','konacik'],['Bodrum Merkez','bodrum-merkez'],['Torba','torba'],['Yalıkavak','yalikavak'],['Gündoğan','gundogan'],['Göltürkbükü','golturkbuku'],['Türkbükü','turkbuku'],['Gölköy','golkoy'],['Güvercinlik','guvercinlik'],['Boğaziçi','bogazici'],['Mumcular','mumcular'],['Yalıçiftlik','yaliciftlik'],['Kızılağaç','kizilagac'],['Çırkan','cirkan'],['Yokuşbaşı','yokusbasi'],['Eskiçeşme','eskicesme'],['Kumbahçe','kumbahce'],['Umurça','umurca'],['Yeniköy','yenikoy'],['Cevat Şakir','cevat-sakir']
].map(([name,slug])=>({name,slug,url:`/bolgeler/${slug}-klima-servisi.html`}));

export const brands = [
 'Arçelik','Beko','Bosch','Siemens','Profilo','Vestel','Regal','Altus','Grundig','Samsung','LG','Daikin','Mitsubishi Electric','Mitsubishi Heavy Industries','Midea','Airfel','Baymak','Demirdöküm','Toshiba','Fujitsu','General','Gree','Sigma','Carrier','York','Hitachi','Panasonic','Viessmann','Vaillant','Haier','Sharp','Hisense','TCL','Kaira','Daylux','Hantech','SEG','Dijitsu','Vestfrost','Rota Climate','Diamond Electric','Dolce Vita','Fujiplus','Electrolux','AEG','Hoover','Candy','Hotpoint','Indesit','Ariston','Whirlpool','Franke','Smeg','Liebherr','Miele','Finlux','Awox','Uğur','Simfer','Esty'
].map(name=>({name,slug:name.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/ı/g,'i').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,''),url:''})).map(b=>({...b,url:`/markalar/${b.slug}-servisi.html`}));

export const guides = [
 ['Klima Bakımı Ne Zaman Yapılmalı?','klima-bakimi-ne-zaman-yapilmali','Klima bakım dönemini kullanım yoğunluğu, ortam koşulları ve üretici kılavuzuna göre planlama yollarını öğrenin.'],
 ['Klima Neden Soğutmaz?','klima-neden-sogutmaz','Soğutma performansı düşen klimada kullanıcı kontrolleri ve servis gerektiren durumlar.'],
 ['Klima Neden Su Akıtır?','klima-su-akitiyor','İç üniteden su gelmesinin olası drenaj ve çalışma koşullarıyla ilişkisini, güvenli gözlem adımlarını öğrenin.'],
 ['Klima Gaz Dolumu Ne Zaman Gerekir?','klima-gaz-dolumu-gerekir-mi','Soğutucu akışkan ihtiyacının hangi belirtilerde teknik olarak değerlendirilmesi gerektiğini ve neden ölçüm gerektiğini öğrenin.'],
 ['Klimadan Kötü Koku Gelmesinin Nedenleri','klima-koku-yapiyor','Klimada kokuya yol açabilecek filtre ve nem koşullarını, kullanıcı bakımının sınırlarını ve servis eşiğini inceleyin.'],
 ['Klima Ses Yapıyor: Olası Nedenler','klima-ses-yapiyor','Klima sesinin hangi çalışma anlarında duyulduğunu kaydedin; değişen sesleri ve servis gerektiren belirtileri ayırt edin.'],
 ['Inverter Klima Arızalarında İlk Kontroller','inverter-klima-arizalari','Inverter klimanın çalışma davranışını, ekrandaki hata kodunu ve güvenli kullanıcı gözlemlerini birlikte değerlendirin.'],
 ['Klima Elektronik Kart Arızası Nasıl Anlaşılır?','klima-elektronik-kart-arizasi','Açılmama, düzensiz çalışma ve hata kodlarının olası nedenlerini öğrenin; elektronik aksam için güvenli servis sınırlarını görün.'],
 ['Klima Montajında Vakum Neden Önemlidir?','klima-montajinda-vakum','Klima kurulumunda vakum işleminin amacını, üretici talimatlarının rolünü ve bu işlemin neden uzman ekipman gerektirdiğini öğrenin.'],
 ['Klima Drenaj Hattı Bakımı','klima-drenaj-bakimi','Yoğuşma suyunun drenajla nasıl tahliye edildiğini ve su sızıntısında hangi gözlemlerin servis için yararlı olduğunu öğrenin.'],
 ['Yazlık Evlerde Klima Sezon Öncesi Kontrolü','yazlik-ev-klima-bakimi','Uzun süre kapalı kalan yazlık ev klimasında sezon öncesi kılavuz kontrollerini ve servis gerektiren belirtileri inceleyin.'],
 ['Bodrum’da Nem ve Tuzlu Havanın Klima Üzerindeki Etkisi','bodrum-nem-klima-bakimi','Kıyı ikliminde nem ve dış ortam koşullarının klima çevresini nasıl etkileyebileceğini ve güvenli bakım sınırlarını öğrenin.'],
 ['VRF Sistemlerde Periyodik Bakım','vrf-sistem-bakimi','VRF sistem bakım planının üretici kılavuzu ve sistem tasarımıyla nasıl ilişkilendiğini; talep öncesi bilgileri öğrenin.'],
 ['Buzdolabı Soğutmuyor: İlk Kontroller','buzdolabi-sogutmuyor','Soğutma düşüşünde kapı, gösterge ve kullanım koşullarını cihazı açmadan nasıl gözlemleyeceğinizi ve ne zaman servis çağıracağınızı öğrenin.'],
 ['Buzdolabından Ses Gelmesi Normal mi?','buzdolabi-ses-yapiyor','Buzdolabının çalışma seslerini ve performans değişikliklerini birlikte değerlendirin; servis için sesi nasıl kaydedeceğinizi öğrenin.'],
 ['Çamaşır Makinesi Neden Sıkmaz?','camasir-makinesi-sikmiyor','Sıkma adımında yük, program ve tahliye belirtilerini model kılavuzuna göre nasıl gözlemleyeceğinizi öğrenin.'],
 ['Çamaşır Makinesi Su Almıyor','camasir-makinesi-su-almiyor','Su almayan çamaşır makinesinde dışarıdan kontrol edilebilen su ve hata kodu bilgilerini, güvenli servis sınırlarıyla inceleyin.'],
 ['Bulaşık Makinesi İçinde Su Kalıyor','bulasik-makinesi-su-birakiyor','Program bitiminde kalan suyu ve tahliye belirtilerini ayırt edin; filtre veya pompa müdahalesinde kılavuz sınırını görün.'],
 ['Bulaşık Makinesi İyi Yıkamıyor','bulasik-makinesi-iyi-yikamiyor','Yıkama sonucu üzerinde etkili program, yükleme ve filtre koşullarını inceleyin; teknik servis gerektiren işaretleri öğrenin.'],
 ['Kurutma Makinesi Neden Kurutmaz?','kurutma-makinesi-kurutmuyor','Kurutma performansında program, yük ve kullanıcı filtresi bakımının rolünü; servis gerektiren belirtileri öğrenin.'],
 ['Beyaz Eşyada Voltaj Dalgalanmasına Karşı Koruma','beyaz-esya-voltaj-koruma','Elektrik kesintisi veya dalgalanma sonrasında cihazı güvenli biçimde gözlemleme ve profesyonel destek eşiğini inceleyin.'],
 ['Teknik Servis Kaydı Açarken Hangi Bilgiler Hazır Olmalı?','servis-cagirirken-hangi-bilgiler','Telefon veya WhatsApp servis talebinde cihaz türü, model, hata kodu, arıza belirtisi ve konum bilgisini nasıl hazırlayacağınızı öğrenin.'],
 ['Klima Filtresi Nasıl ve Ne Sıklıkla Temizlenir?','klima-filtre-temizligi','Klima filtresinin bakım periyodunu ve temizleme yöntemini model kılavuzuna göre belirleyin; iç üniteye müdahale sınırını öğrenin.'],
 ['Klimayı Daha Verimli Kullanmak İçin 10 Teknik İpucu','klima-enerji-verimliligi','Klima ayarı, filtre bakımı, güneş yükü ve kapı-pencere koşullarının verimli kullanımla ilişkisini gözden geçirin.'],
 ['Beyaz Eşya Ömrünü Uzatmak İçin Bakım Rehberi','beyaz-esya-bakim-rehberi','Ev tipi cihazlarda kullanıcı bakımını teknik iç bakımdan ayırın; rutinler için model kullanım kılavuzunu izleyin.']
].map(([title,slug,description])=>({title,slug,description,url:`/bilgi-merkezi/${slug}.html`}));

// Editorial relationships and safe, topic-specific guidance. Claims stay within
// the information held by the project; device-specific instructions defer to
// the manufacturer's model manual.
export const serviceDetails = {
 'klima-tamiri':{icon:'wrench',requestCases:['Soğutma veya ısıtma performansı düştüyse','İç üniteden su, koku ya da alışılmadık ses geliyorsa','Cihaz uyarı veriyor veya beklenmedik biçimde duruyorsa'],beforeContact:['İç ve dış ünitenin çalışma durumunu gözlemleyin.','Varsa hata kodunu ve belirtinin ne zaman başladığını not edin.'],guideSlugs:['klima-neden-sogutmaz','klima-su-akitiyor','klima-ses-yapiyor','klima-elektronik-kart-arizasi'],faq:[['Klima soğutmuyorsa servis öncesinde ne paylaşmalıyım?','Model bilgisi, görünen uyarı kodu, çalışma modu ve soğutma belirtisinin ne zaman başladığı ilk değerlendirmeyi kolaylaştırır.'],['Klimadan su gelmesi normal midir?','Drenaj ve çalışma koşulları etkili olabilir. Su akışı sürerse cihazı kapatıp konumu ve ne zaman başladığını bildirin.']]},
 'klima-bakimi':{icon:'snow',requestCases:['Sezon öncesi genel çalışma kontrolü gerektiğinde','Filtre veya drenaj bakımı planlanırken','Cihazın hava akışı ya da performansı değiştiğinde'],beforeContact:['Cihazın modelini ve son bakım dönemini not edin.','Filtre kullanıcının erişimine açıksa kılavuza göre kontrol edin.'],guideSlugs:['klima-bakimi-ne-zaman-yapilmali','yazlik-ev-klima-bakimi','bodrum-nem-klima-bakimi','klima-filtre-temizligi','klima-enerji-verimliligi'],faq:[['Klima bakımı ne zaman planlanmalı?','Kullanım yoğunluğu, ortam ve üreticinin bakım önerisi dikkate alınır. Model kılavuzundaki periyotları izleyin.'],['Filtreyi kendim temizleyebilir miyim?','Yalnızca kullanım kılavuzunda kullanıcı bakımı olarak belirtilen filtreyi, tarif edilen şekilde temizleyin; iç üniteyi açmayın.']]},
 'klima-montaji':{icon:'installation',requestCases:['Yeni cihaz kurulumu veya cihazın yerinin değiştirilmesi gerektiğinde','Mevcut sistem sökülecek ya da yeniden kurulacaksa'],beforeContact:['Cihazın marka-modelini ve iç/dış ünite bilgilerini paylaşın.','Kurulum yapılacak alanı ve mevcut bağlantıları tarif edin; keşif veya uygunluk teyidini telefonla alın.'],guideSlugs:['klima-montajinda-vakum'],faq:[['Klima montajında hangi bilgiler gerekir?','Cihaz modeli, iç ve dış ünitenin kurulacağı alanlar ve mevcut tesisat bilgisi ilk planlama için yararlıdır.'],['Sökülen klima başka bir yere kurulabilir mi?','Uygunluk cihaz, bağlantı ve yeni alan koşullarına bağlıdır; işlem öncesinde teknik değerlendirme gerekir.']]},
 'klima-gaz-dolumu':{icon:'gauge',requestCases:['Soğutma performansında belirgin düşüş olduğunda','Gaz işlemi gerektiğinden şüphelenildiğinde'],beforeContact:['Performans değişikliğinin ne zaman başladığını not edin.','Dış ünitede gözle görülen olağan dışı durum varsa tarif edin; boru veya vana bağlantılarına dokunmayın.'],guideSlugs:['klima-gaz-dolumu-gerekir-mi','klima-neden-sogutmaz'],faq:[['Her soğutmama sorununda gaz dolumu gerekir mi?','Hayır. Performans düşüşünün farklı nedenleri olabilir; gaz ihtiyacı ölçüm ve sistem kontrolüyle değerlendirilir.'],['Gazı kendim tamamlayabilir miyim?','Hayır. Soğutucu akışkan ve basınçlı devre işlemleri kullanıcı müdahalesi için uygun değildir; teknik servis değerlendirmesi gerekir.']]},
 'klima-temizligi':{icon:'clean',requestCases:['Filtre temizliği dışında bakım ihtiyacı varsa','Hava akışı veya koku sorunu sürüyorsa'],beforeContact:['Kokunun veya hava akışı değişikliğinin hangi durumda görüldüğünü not edin.','Yalnızca kılavuzun kullanıcıya açtığı filtre bakımını uygulayın; kimyasalı cihaz içine püskürtmeyin.'],guideSlugs:['klima-koku-yapiyor','klima-filtre-temizligi','klima-drenaj-bakimi'],faq:[['Kötü koku filtre kaynaklı olabilir mi?','Filtre bakımı etkili olabilir; koku devam ederse başka bileşenlerin kontrolü gerekebilir.'],['İç üniteyi sökerek temizlemeli miyim?','Hayır. Kullanıcı bakım sınırını model kılavuzu belirler; iç parçaların sökülmesini servise bırakın.']]},
 'klima-kart-tamiri':{icon:'circuit',requestCases:['Cihaz açılmıyor veya kendiliğinden duruyorsa','Ekranda hata kodu ya da düzensiz çalışma görülüyorsa'],beforeContact:['Ekrandaki hata kodunu fotoğraflayın veya yazın.','Sorunun elektrik kesintisi ya da yeniden başlatma sonrasında başlayıp başlamadığını belirtin.'],guideSlugs:['klima-elektronik-kart-arizasi','inverter-klima-arizalari'],faq:[['Hata kodu elektronik kart arızası anlamına mı gelir?','Tek başına kod kesin tanı koydurmaz. Model kılavuzundaki açıklama ve teknik ölçüm gerekir.'],['Kartı açıp bağlantıları kontrol edebilir miyim?','Hayır. Elektronik ve elektrik bağlantılarına müdahale etmeyin; cihazı güvenli biçimde kapatıp servisle görüşün.']]},
 'vrf-vrv-servisi':{icon:'vrf',requestCases:['Birden fazla iç ünitede eş zamanlı performans değiştiğinde','Kontrol panelinde uyarı kodu görüldüğünde','Planlı sistem kontrolü gerektiğinde'],beforeContact:['Sistem ve kontrol paneli modelini paylaşın.','Etkilenen iç üniteleri ve varsa hata kodlarını not edin.'],guideSlugs:['vrf-sistem-bakimi'],faq:[['VRF sistem talebinde hangi bilgiler yararlı olur?','Dış ünite/sistem modeli, kontrol panelindeki kod ve etkilenen iç üniteler ilk değerlendirmeyi destekler.'],['Bir iç ünite çalışmazken diğerleri çalışıyorsa ne yapmalıyım?','Ünite ve kontrol ayarları değişkenlik gösterebilir; kodları not edip sistem bağlantılarına müdahale etmeden servisle görüşün.']]},
 'multi-split-klima-servisi':{icon:'multi',requestCases:['Sisteme bağlı iç ünitelerden biri farklı çalıştığında','Birden fazla odada soğutma/ısıtma dengesi değiştiğinde'],beforeContact:['Çalışması değişen iç üniteleri ve seçili modları not edin.','Sistem modelini ve belirtinin görüldüğü zamanı paylaşın.'],guideSlugs:['klima-neden-sogutmaz','klima-ses-yapiyor'],faq:[['Tek iç ünite çalışmıyorsa diğerlerini kapatmalı mıyım?','Sistemin kullanımını model kılavuzuna göre değerlendirin; olağan dışı ses, koku veya uyarı varsa cihazı kapatıp servisle görüşün.'],['Multi split talebi için ne hazırlamalıyım?','Sistemin modelini ve sorun görülen iç üniteleri belirtmeniz yeterli bir başlangıç sağlar.']]},
 'beyaz-esya-tamiri':{icon:'appliance',requestCases:['Cihaz açılmıyor, programı tamamlamıyor veya performansı değiştiyse','Birden fazla belirti ya da hata kodu varsa'],beforeContact:['Cihazın tam modelini ve hata kodunu not edin.','Belirtinin hangi program veya kullanım anında oluştuğunu tarif edin.'],guideSlugs:['beyaz-esya-voltaj-koruma','beyaz-esya-bakim-rehberi','servis-cagirirken-hangi-bilgiler'],faq:[['Beyaz eşya servis kaydı için neler gerekli?','Ürün türü, model etiketi, hata kodu ve belirtinin ne zaman başladığı ilk değerlendirmeye yardımcı olur.'],['Cihazı arıza sırasında çalıştırmaya devam edeyim mi?','Su kaçağı, yanık kokusu, kıvılcım veya olağan dışı ısınma varsa kullanmayı bırakın ve servisle görüşün.']]},
 'buzdolabi-servisi':{icon:'fridge',requestCases:['Soğutucu veya dondurucu bölümünün sıcaklığı değiştiyse','Kapı kapanması, ses veya çalışma düzeni farklılaştıysa'],beforeContact:['Gösterge sıcaklığını, kapı kapanmasını ve belirtinin süresini not edin.','Gıdaların güvenliği konusunda üretici ve gıda güvenliği yönergelerini izleyin.'],guideSlugs:['buzdolabi-sogutmuyor','buzdolabi-ses-yapiyor','beyaz-esya-voltaj-koruma'],faq:[['Buzdolabı soğutmuyorsa ilk hangi bilgi gerekir?','Model, gösterge durumu, soğutma değişikliğinin ne zaman başladığı ve kapı kullanım bilgisi yararlıdır.'],['Buzdolabından aralıklı ses gelmesi arıza mıdır?','Bazı çalışma sesleri modele özgü olabilir. Ses yeni, sürekli veya olağan dışıysa kaynağını tarif ederek servis görüşü alın.']]},
 'camasir-makinesi-servisi':{icon:'washer',requestCases:['Su alma, tahliye veya sıkma tamamlanmıyorsa','Program yarıda kalıyor ya da uyarı kodu görünüyorsa'],beforeContact:['Ekrandaki kodu ve program adımını not edin.','Kapak çevresinde su sızıntısı olup olmadığını gözlemleyin; filtreyi açmadan önce kılavuz güvenlik adımlarına bakın.'],guideSlugs:['camasir-makinesi-sikmiyor','camasir-makinesi-su-almiyor','servis-cagirirken-hangi-bilgiler'],faq:[['Makine sıkmıyorsa servis kaydına ne yazayım?','Program, yük miktarı, suyun tahliye olup olmadığı ve ekrandaki kod ilk değerlendirmeyi kolaylaştırır.'],['Filtre kapağını kendim açabilir miyim?','Model kılavuzundaki kullanıcı bakım adımlarını ve güvenlik uyarılarını izleyin. Emin değilseniz müdahale etmeyin; filtrede sıcak su kalabilir.']]},
 'bulasik-makinesi-servisi':{icon:'dishwasher',requestCases:['Su almıyor veya program sonunda su bırakıyorsa','Yıkama sonucu ya da çalışma sesi değiştiyse'],beforeContact:['Program kodunu, su giriş ve çıkış belirtisini not edin.','Püskürtme kollarında görünür engel olup olmadığını kullanıcı kılavuzuna göre kontrol edin.'],guideSlugs:['bulasik-makinesi-su-birakiyor','bulasik-makinesi-iyi-yikamiyor'],faq:[['Program sonunda makinede su kalırsa ne yapmalıyım?','Bir miktar suyun hangi seviyede kaldığını ve makinenin tahliye sesi verip vermediğini belirtin; pompa ve tesisatı sökmeyin.'],['Bulaşıklar iyi yıkanmıyorsa hangi bilgileri paylaşayım?','Program, yükleme düzeni, deterjan tipi ve görülen hata kodu yararlı olur.']]},
 'kurutma-makinesi-servisi':{icon:'dryer',requestCases:['Çamaşırlar kuruma süresinin sonunda nemli kalıyorsa','Cihaz uyarı veriyor veya hava akışı değiştiyse'],beforeContact:['Programı, yük miktarını ve filtre uyarısını not edin.','Yalnızca kullanıcı kılavuzunda tarif edilen tüy filtresi bakımını yapın.'],guideSlugs:['kurutma-makinesi-kurutmuyor','beyaz-esya-bakim-rehberi'],faq:[['Kurutma süresi uzarsa ne paylaşmalıyım?','Program, yük miktarı, filtre uyarısı ve kurutma süresindeki değişim ilk değerlendirmeye yardımcı olur.'],['Cihazın havalandırma kanallarını sökebilir miyim?','Sökme ve iç temizlik işlemleri model kılavuzunda kullanıcı bakımı olarak belirtilmedikçe servise bırakılmalıdır.']]},
 'derin-dondurucu-servisi':{icon:'freezer',requestCases:['Dondurma performansı veya iç sıcaklık değiştiyse','Uyarı kodu, alarm veya olağan dışı ses varsa'],beforeContact:['Gösterge/alarm bilgisini ve kesintinin ne zaman fark edildiğini not edin.','Gıdaların çözülüp çözülmediğini kontrol edin; çözülmüş gıdalar için güvenli saklama yönergelerini izleyin.'],guideSlugs:['buzdolabi-sogutmuyor','beyaz-esya-voltaj-koruma'],faq:[['Dondurucu alarmında cihazın fişini çekmeli miyim?','Model kılavuzundaki alarm adımlarını izleyin. Yanık kokusu, kıvılcım veya elektrik riski varsa güvenliyse enerjiyi kesin ve servis çağırın.'],['Servis talebinde hangi sıcaklık bilgisini vermeliyim?','Varsa paneldeki sıcaklığı, alarm kodunu ve cihazın yaklaşık ne zamandır bu durumda olduğunu paylaşın.']]},
 'ankastre-servisi':{icon:'oven',requestCases:['Fırın, ocak veya ankastre cihazın işlevi değiştiyse','Kontrol panelinde uyarı ya da kesinti oluştuysa'],beforeContact:['Ankastre ürünün türü ve model etiketini paylaşın.','Belirtinin hangi fonksiyonda ortaya çıktığını belirtin; cihazı yerinden çıkarmayın.'],guideSlugs:['beyaz-esya-voltaj-koruma','beyaz-esya-bakim-rehberi'],faq:[['Ankastre cihaz servisinde cihazı yerinden çıkarmalı mıyım?','Hayır. Elektrik veya gaz bağlantıları bulunabileceğinden ürünü sökmeden servisle görüşün.'],['Talebe hangi ürün bilgisi eklenmeli?','Fırın, ocak veya diğer ankastre ürünün türü, model etiketi ve arıza belirtisini paylaşın.']]}
};

export const serviceGuideMap = Object.fromEntries(services.map(s=>[s.slug,serviceDetails[s.slug].guideSlugs]));
export const serviceRelatedMap = {
 'klima-tamiri':['klima-bakimi','klima-gaz-dolumu','klima-temizligi'],
 'klima-bakimi':['klima-temizligi','klima-tamiri','klima-montaji'],
 'klima-montaji':['klima-bakimi','klima-tamiri'],
 'klima-gaz-dolumu':['klima-tamiri','klima-bakimi'],
 'klima-temizligi':['klima-bakimi','klima-tamiri'],
 'klima-kart-tamiri':['klima-tamiri','vrf-vrv-servisi'],
 'vrf-vrv-servisi':['multi-split-klima-servisi','klima-bakimi','klima-tamiri'],
 'multi-split-klima-servisi':['vrf-vrv-servisi','klima-tamiri','klima-bakimi'],
 'beyaz-esya-tamiri':['buzdolabi-servisi','camasir-makinesi-servisi','bulasik-makinesi-servisi'],
 'buzdolabi-servisi':['derin-dondurucu-servisi','beyaz-esya-tamiri'],
 'camasir-makinesi-servisi':['kurutma-makinesi-servisi','bulasik-makinesi-servisi','beyaz-esya-tamiri'],
 'bulasik-makinesi-servisi':['camasir-makinesi-servisi','ankastre-servisi','beyaz-esya-tamiri'],
 'kurutma-makinesi-servisi':['camasir-makinesi-servisi','beyaz-esya-tamiri'],
 'derin-dondurucu-servisi':['buzdolabi-servisi','beyaz-esya-tamiri'],
 'ankastre-servisi':['bulasik-makinesi-servisi','beyaz-esya-tamiri']
};

export const guideDetails = {
 'klima-bakimi-ne-zaman-yapilmali':{category:'Klima bakımı',answer:'Bakım zamanı; kullanım yoğunluğu, ortam koşulları ve cihaz üreticisinin kılavuzundaki periyoda göre belirlenir. Performans düşüşü varsa sezonu beklemeden kontrol talep edilebilir.',diagnosticHeading:'Bakım ihtiyacını gösteren değişiklikler',observations:['Hava akışı veya soğutma/ısıtma performansında düşüş','Filtre uyarısı ya da erişilebilir filtrede belirgin kir','Sezon başında uzun süre kullanılmamış cihaz'],safeHeading:'Kullanıcının güvenle yapabileceği',safeChecks:['Kullanım kılavuzundaki filtre bakım aralığını kontrol edin.','Filtreyi yalnızca model talimatı izin veriyorsa temizleyip tamamen kuruduktan sonra yerine takın.'],serviceTrigger:'İç üniteyi açma, elektrikli bölümlere veya soğutucu devreye müdahale etme işlemlerini servise bırakın.',tellService:'Modeli, son bakım zamanını ve fark ettiğiniz performans değişimini paylaşın.',serviceSlugs:['klima-bakimi','klima-temizligi'],related:['yazlik-ev-klima-bakimi','klima-filtre-temizligi','bodrum-nem-klima-bakimi']},
 'klima-neden-sogutmaz':{category:'Arıza belirtileri',answer:'Soğutmanın azalması ayar, filtre/hava akışı, ortam yükü veya teknik bir arızayla ilişkili olabilir. Tek belirtiye bakarak gaz eksikliği ya da parça arızası sonucu çıkarılamaz.',diagnosticHeading:'Önce hangi değişikliği gözlemleyin?',observations:['Cihazın hangi modda ve ayarda çalıştığı','İç üniteden hava çıkıp çıkmadığı','Belirtinin ne zaman başladığı ve ekranda kod olup olmadığı'],safeHeading:'Elektrik içermeyen ilk kontroller',safeChecks:['Mod ve sıcaklık ayarını kullanım kılavuzuyla karşılaştırın.','Filtre kullanıcıya erişilebilir ise kılavuza göre kontrol edin.'],serviceTrigger:'Filtre/ayar kontrolünden sonra sorun sürüyorsa veya cihaz uyarı veriyorsa soğutucu hatları ve elektrikli aksamı açmadan servis isteyin.',tellService:'Marka-model, seçili mod, hata kodu ve soğutma düşüşünün başlangıç zamanını not edin.',serviceSlugs:['klima-tamiri','klima-gaz-dolumu','klima-bakimi'],related:['klima-gaz-dolumu-gerekir-mi','klima-filtre-temizligi','klima-elektronik-kart-arizasi']},
 'klima-su-akitiyor':{category:'Arıza belirtileri',answer:'İç üniteden su gelmesi drenaj tahliyesi, yoğuşma veya kurulum koşullarıyla ilgili olabilir. Kaynağı görmeden cihazı sökmek güvenli değildir.',diagnosticHeading:'Sızıntının koşulunu kaydedin',observations:['Suyun iç üniteden mi boru çevresinden mi geldiği','Akışın soğutma sırasında mı, kapatıldıktan sonra mı başladığı','Sızıntının sürekli olup olmadığı'],safeHeading:'Alanı güvenli tutun',safeChecks:['Su elektrik prizine veya kabloya yaklaşıyorsa cihaza dokunmayın; güvenliyse enerjiyi kesin.','Suyun aktığı yeri ve zamanı fotoğrafla kaydedin.'],serviceTrigger:'Drenaj hattını açmak, iç üniteyi sökmek veya elektrik bağlantılarına müdahale etmek gerekebilir; bu işlemleri teknik servise bırakın.',tellService:'Ünite konumu, sızıntı zamanı, akış miktarı ve varsa son bakım bilgisini paylaşın.',serviceSlugs:['klima-tamiri','klima-drenaj-bakimi','klima-temizligi'],related:['klima-drenaj-bakimi','klima-bakimi-ne-zaman-yapilmali','klima-koku-yapiyor']},
 'klima-gaz-dolumu-gerekir-mi':{category:'Arıza belirtileri',answer:'Soğutucu akışkan normal kullanımda düzenli olarak tüketilen bir yakıt değildir. Dolum kararı ancak sistem kontrolü ve ölçüm sonrası verilebilir; kaçak şüphesi varsa neden araştırılmalıdır.',diagnosticHeading:'Gaz ihtiyacı tek belirtiyle anlaşılmaz',observations:['Soğutma performansı ve çalışma süresindeki değişim','İç/dış ünite davranışı ve görünen hata kodu','Sorunun bakım veya montaj sonrasında ortaya çıkıp çıkmadığı'],safeHeading:'Gözlemleyin, devreye dokunmayın',safeChecks:['Kullanım ayarlarını ve filtre bakımını kılavuza göre kontrol edin.','Boru bağlantılarını, vanaları veya servis portlarını gevşetmeyin.'],serviceTrigger:'Soğutucu akışkan ve basınçlı hat işlemleri yetkin teknik müdahale gerektirir. Gaz eklemeyin; arıza değerlendirmesi isteyin.',tellService:'Modeli, performans değişikliğini ve önceki bakım/kurulum tarihini bildirin.',serviceSlugs:['klima-gaz-dolumu','klima-tamiri'],related:['klima-neden-sogutmaz','klima-montajinda-vakum']},
 'klima-koku-yapiyor':{category:'Bakım ve kullanım',answer:'Koku; filtre, yoğuşma ve iç ünitedeki nem koşulları gibi farklı nedenlerle oluşabilir. Koku türü tek başına arızayı teşhis etmez.',diagnosticHeading:'Kokunun ne zaman oluştuğunu ayırt edin',observations:['İlk açılışta mı yoksa sürekli çalışırken mi hissedildiği','Kokunun belirli mod veya süreden sonra artıp artmadığı','Kokuya su sızıntısı veya sesin eşlik edip etmediği'],safeHeading:'Filtre kontrolünü kılavuza göre yapın',safeChecks:['Kullanıcı filtresini model kılavuzuna uygun şekilde kontrol edin.','Filtre tamamen kuruduktan sonra takın; iç kısma parfüm veya kimyasal püskürtmeyin.'],serviceTrigger:'Koku sürerse, yanık benzeri bir koku varsa veya duman görülürse cihazı kapatın; elektrikli ve iç bileşenleri açmayın.',tellService:'Koku türünü, çalışma modunu, başlangıç zamanını ve filtre bakımını belirtin.',serviceSlugs:['klima-temizligi','klima-bakimi'],related:['klima-filtre-temizligi','klima-drenaj-bakimi','klima-bakimi-ne-zaman-yapilmali']},
 'klima-ses-yapiyor':{category:'Arıza belirtileri',answer:'Hava akışı ve fan gibi çalışma sesleri modele göre değişebilir. Yeni başlayan, artan veya metalik/titreşimli sesler ayrıca değerlendirilmelidir.',diagnosticHeading:'Sesi ve çalışma anını kaydedin',observations:['Sesin iç üniteden mi dış üniteden mi geldiği','Fan, ilk çalışma veya duruş anında olup olmadığı','Sesle birlikte performans düşüşü ya da hata kodu bulunup bulunmadığı'],safeHeading:'Görsel ve işitsel gözlem yeterli',safeChecks:['Cihaz çevresinde hava giriş/çıkışını kapatan eşya olup olmadığını kontrol edin.','Sesi kısa bir kayıtla alın; dış ünitedeki parçalara dokunmayın.'],serviceTrigger:'Gövdeyi açmayın ve fana müdahale etmeyin. Sürtme, yanık kokusu veya yoğun titreşim varsa cihazı kapatıp servisle görüşün.',tellService:'Ses kaydı, ünite tarafı, çalışma modu ve eşlik eden belirtileri iletin.',serviceSlugs:['klima-tamiri','klima-bakimi'],related:['klima-neden-sogutmaz','klima-koku-yapiyor']},
 'inverter-klima-arizalari':{category:'Arıza belirtileri',answer:'Inverter sistemler kapasiteyi ihtiyaca göre değiştirebilir; kompresörün sürekli aynı hızda çalışmaması tek başına arıza anlamına gelmez. Değişen performans ve uyarılar birlikte değerlendirilir.',diagnosticHeading:'Normal çalışma ile arıza belirtisini ayırın',observations:['Ekrandaki hata kodu ve çalışma modu','Belirtinin ne zaman başladığı ve ortam değişikliği','İç/dış ünitede olağan dışı ses, koku veya duruş'],safeHeading:'Kılavuz sınırında kalın',safeChecks:['Uzaktan kumanda ayarlarını ve filtre bakım uyarısını kontrol edin.','Cihazı art arda açıp kapatmak yerine kılavuzdaki kullanıcı adımlarını uygulayın.'],serviceTrigger:'Elektronik kart, inverter modülü ve güç elektroniğini açmayın. Uyarı tekrarlıyor veya yanık kokusu varsa cihazı kullanmayın.',tellService:'Tam model, kod, seçili mod ve sorunun tekrar sıklığını paylaşın.',serviceSlugs:['klima-tamiri','klima-kart-tamiri'],related:['klima-elektronik-kart-arizasi','klima-neden-sogutmaz']},
 'klima-elektronik-kart-arizasi':{category:'Arıza belirtileri',answer:'Açılmama, düzensiz çalışma veya hata kodu elektronik kontrol sorunlarıyla ilişkili olabilir; aynı belirtiler başka arızalarda da görülebilir. Kesin tanı ölçüm gerektirir.',diagnosticHeading:'Uyarı bilgisini kaydedin',observations:['Ekranda görünen kod veya ışık dizisi','Cihazın açılma/kapanma düzeni','Sorunun elektrik kesintisi veya bakım sonrası başlayıp başlamadığı'],safeHeading:'Yalnızca dışarıdan gözlem',safeChecks:['Kodu ve kontrol panelini fotoğraflayın.','Kullanım kılavuzunda açıklanan kullanıcı reseti varsa yalnızca bir kez uygulayın.'],serviceTrigger:'Kart kapağını açmayın; kondansatör ve şebeke bağlantıları tehlikeli gerilim taşıyabilir. Duman veya yanık kokusunda güvenliyse enerjiyi kesin.',tellService:'Model, kod, kesinti geçmişi ve gözlenen açılma davranışını paylaşın.',serviceSlugs:['klima-kart-tamiri','klima-tamiri'],related:['inverter-klima-arizalari','klima-ses-yapiyor']},
 'klima-montajinda-vakum':{category:'Montaj ve kurulum',answer:'Montajda vakum uygulaması, üreticinin kurulum talimatına uygun olarak soğutucu devredeki hava ve nemin tahliyesine yönelik profesyonel bir işlemdir.',diagnosticHeading:'Kurulum sonrası hangi bilgileri sorun?',observations:['Kılavuzda vakum ve devreye alma adımlarının nasıl tarif edildiği','Montajı yapan servisin kurulum kontrolünü nasıl belgelediği','Kurulum sonrası görülen hata veya performans değişikliği'],safeHeading:'Kontrolü belge üzerinden yapın',safeChecks:['Cihaz kılavuzunda kullanıcıya verilen kurulum/garanti koşullarını okuyun.','Vakum pompası, vana ve soğutucu devreye kendiniz müdahale etmeyin.'],serviceTrigger:'Soğutucu devrenin vakumlanması ve bağlantı kontrolü uzman ekipman gerektirir; yalnızca yetkin servis personelince yapılmalıdır.',tellService:'Cihaz modeli, montaj zamanı ve kurulum sonrası gözlenen durumu bildirin.',serviceSlugs:['klima-montaji','klima-gaz-dolumu'],related:['klima-gaz-dolumu-gerekir-mi','klima-bakimi-ne-zaman-yapilmali']},
 'klima-drenaj-bakimi':{category:'Bakım ve kullanım',answer:'Drenaj, klimanın çalışma sırasında oluşan yoğuşma suyunu tahliye eder. Tıkanma veya eğim/bağlantı sorunu suyun iç üniteden gelmesine yol açabilir.',diagnosticHeading:'Su tahliyesini gözlemleyin',observations:['İç ünitede veya duvarda görülen su izi','Sızıntının yalnızca soğutmada mı ortaya çıktığı','Yakın zamanda yapılan montaj veya bakım olup olmadığı'],safeHeading:'Erişilebilir yüzeyleri kuru tutun',safeChecks:['Suyun elektrik hattı ve prize ulaşıp ulaşmadığını uzaktan gözlemleyin.','Drenaj hortumunu çekmeyin, tel sokmayın veya basınçlı hava vermeyin.'],serviceTrigger:'Hat temizliği, eğim ve iç ünite bağlantısı kontrolü servis işlemidir. Su elektriğe yaklaşıyorsa cihaza dokunmayın.',tellService:'Sızıntının yeri, zamanı, çalışma modu ve son bakım/montaj bilgisini iletin.',serviceSlugs:['klima-drenaj-bakimi','klima-tamiri','klima-temizligi'],related:['klima-su-akitiyor','klima-bakimi-ne-zaman-yapilmali']},
 'yazlik-ev-klima-bakimi':{category:'Klima bakımı',answer:'Uzun süre kapalı kalan bir klimayı sezon başında kullanmadan önce kılavuzdaki temel filtre ve dış görünüş kontrollerini yapın; anormal belirti sürerse servis kontrolü planlayın.',diagnosticHeading:'Sezon öncesi çalışma koşulları',observations:['Cihazın ne kadar süredir kullanılmadığı','Depolama/kapalı kalma döneminden sonra görülen koku veya su','İlk çalışmada hava akışı ve hata göstergesi'],safeHeading:'İlk çalıştırmada güvenli sınırlar',safeChecks:['Kullanıcı filtresini kılavuz izin veriyorsa temizleyin.','Ünite çevresini gözle kontrol edin; dış ünitede çalışma alanını kapatan nesneleri uzaktan fark edin.'],serviceTrigger:'Koku, sızıntı, hata kodu veya performans düşüşü sürerse cihazı açıp temizlemeye çalışmayın; servis talebi oluşturun.',tellService:'Konutun uzun süre kapalı kaldığını, son kullanım tarihini ve ilk çalışmadaki belirtileri bildirin.',serviceSlugs:['klima-bakimi','klima-tamiri'],related:['klima-bakimi-ne-zaman-yapilmali','bodrum-nem-klima-bakimi','klima-filtre-temizligi']},
 'bodrum-nem-klima-bakimi':{metaTitle:'Bodrum’da Nem ve Tuzlu Havanın Klima Etkisi | Dost Teknik',category:'Klima bakımı',answer:'Nemli ve kıyı koşullarında dış ünitenin bulunduğu çevre, hava dolaşımı ve yüzey kirlenmesi düzenli gözlem gerektirir. Bölgesel koşullar tek başına bir arıza tanısı değildir.',diagnosticHeading:'Çevre koşullarını da kaydedin',observations:['Dış ünitenin çevresinde hava akışını engelleyen yeni bir durum','Filtre veya dış yüzeyde görünen kir birikimi','Performans değişikliğinin yoğun nemli dönemlerle ilişkisi'],safeHeading:'Güvenli kullanıcı gözlemi',safeChecks:['Dış ünitenin çevresini uzaktan gözle kontrol edin; kapağı veya ızgarayı açmayın.','Filtre bakımı için üretici kılavuzundaki kullanıcı adımlarını izleyin.'],serviceTrigger:'Metal yüzeylerde hasar, su sızıntısı veya elektrik riski fark edilirse parçaya dokunmadan teknik inceleme isteyin.',tellService:'Cihazın konumunu, çevre koşullarını ve bakım geçmişini belirtin.',serviceSlugs:['klima-bakimi','klima-temizligi'],related:['klima-bakimi-ne-zaman-yapilmali','yazlik-ev-klima-bakimi','klima-enerji-verimliligi']},
 'vrf-sistem-bakimi':{category:'Klima bakımı',answer:'VRF bakımında kontrol kapsamı sistem tasarımına, üretici talimatına ve bağlı iç ünite sayısına göre değişir. Periyodu ve işlemleri yetkili proje/cihaz dokümanından teyit edin.',diagnosticHeading:'Bakım planlamasında gereken sistem bilgisi',observations:['Dış ünite ve kontrol sistemi modeli','Kontrol panelinde kayıtlı hata kodları','Etkilenen iç üniteler ve son bakım zamanı'],safeHeading:'Kullanıcı panelini izleyin',safeChecks:['Panelde görünen kodu ve bağlı ünite adlarını not edin.','Ünitelerin çalışma ayarlarını değiştirmeden önce sistem kullanım talimatına bakın.'],serviceTrigger:'Soğutucu devre, adresleme, elektrik panosu veya merkezi kontrol sistemine müdahale etmeyin.',tellService:'Sistem şeması/modeli, kod, etkilenen üniteler ve erişim koşullarını iletin.',serviceSlugs:['vrf-vrv-servisi','klima-bakimi'],related:['klima-bakimi-ne-zaman-yapilmali','klima-montajinda-vakum']},
 'buzdolabi-sogutmuyor':{category:'Beyaz eşya arızaları',answer:'Soğutma düşüşü kapının tam kapanmaması, yeni/sıcak yiyecek yükü, sıcaklık ayarı veya teknik bir sorunla ilişkili olabilir. Gıdaların güvenliğini ayrıca değerlendirin.',diagnosticHeading:'Önce görünür koşulları kaydedin',observations:['Kapıların tam kapanıp kapanmadığı','Gösterge sıcaklığı ve alarm durumu','Elektrik kesintisi, yoğun yükleme veya yer değişimi yaşanıp yaşanmadığı'],safeHeading:'Cihazı açmadan kontrol edin',safeChecks:['Kapı çevresinde kapanmayı engelleyen eşya olup olmadığına bakın.','Ayarları model kılavuzundaki önerilerle karşılaştırın; arka kapağı veya soğutma sistemini açmayın.'],serviceTrigger:'Yanık kokusu, kablo hasarı veya tekrarlayan alarm varsa güvenliyse enerjiyi kesin ve destek alın. Gıdalar için güvenli saklama/atım yönergelerini izleyin.',tellService:'Modeli, gösterge değerini, alarmı ve soğutma değişikliğinin süresini paylaşın.',serviceSlugs:['buzdolabi-servisi','beyaz-esya-tamiri'],related:['buzdolabi-ses-yapiyor','beyaz-esya-voltaj-koruma']},
 'buzdolabi-ses-yapiyor':{category:'Beyaz eşya arızaları',answer:'Buzdolabında fan, kompresör ve soğutma çevrimi farklı sesler çıkarabilir. Yeni başlayan, sürekli artan veya performans değişikliğiyle birlikte görülen ses inceleme gerektirir.',diagnosticHeading:'Sesin kaynağını ve düzenini ayırt edin',observations:['Sesin kapı açıldığında değişip değişmediği','Sesin aralıklı mı sürekli mi duyulduğu','Soğutma performansı veya alarmın aynı anda değişip değişmediği'],safeHeading:'Kayıt alın, parçaya dokunmayın',safeChecks:['Cihazın dengeli durup durmadığını dışarıdan gözlemleyin.','Sesi kısa kayıtla belgeleyin; arka panele veya fana erişmeye çalışmayın.'],serviceTrigger:'Tıkırtı şiddetlenirse, yanık kokusu olursa veya cihaz soğutmayı bırakırsa kullanımı güvenli şekilde durdurup servisle görüşün.',tellService:'Ses kaydı, cihaz modeli, konum ve soğutma durumunu paylaşın.',serviceSlugs:['buzdolabi-servisi','beyaz-esya-tamiri'],related:['buzdolabi-sogutmuyor','beyaz-esya-voltaj-koruma']},
 'camasir-makinesi-sikmiyor':{category:'Beyaz eşya arızaları',answer:'Sıkma aşamasına geçmeme; dengesiz yük, seçili program veya su tahliye koşullarıyla ilişkili olabilir. Her modelin kullanıcı adımları farklıdır.',diagnosticHeading:'Programın hangi noktada kaldığını belirleyin',observations:['Tamburdaki yükün tek parça veya aşırı dolu olup olmadığı','Programda sıkma/hassas seçeneklerinin durumu','Makinede su kalıp kalmadığı ve ekrandaki kod'],safeHeading:'Panel ve yük dışında işlem yapmayın',safeChecks:['Program seçimini ve yük miktarını kılavuza göre kontrol edin.','Su kaçağı yoksa ekrandaki uyarıyı not edin; filtre kapağını kılavuz izin vermedikçe açmayın.'],serviceTrigger:'Kapak kilidi, pompa, elektrik bağlantısı veya filtre sökümü için cihazı açmayın. Sızıntı/yanık kokusunda kullanımı durdurun.',tellService:'Program, yük türü, su kalıp kalmadığı ve hata kodunu bildirin.',serviceSlugs:['camasir-makinesi-servisi','beyaz-esya-tamiri'],related:['camasir-makinesi-su-almiyor','servis-cagirirken-hangi-bilgiler']},
 'camasir-makinesi-su-almiyor':{category:'Beyaz eşya arızaları',answer:'Su almama su girişinin kapalı olması, tesisat koşulu veya cihazın su giriş sistemiyle ilgili olabilir. Hortum ve filtre sökümü model kılavuzuna ve güvenlik adımlarına bağlıdır.',diagnosticHeading:'Dışarıdan gözlemlenebilecekler',observations:['Su şebekesinde kesinti olup olmadığı','Ekrandaki hata kodu ve programın hangi aşamada kaldığı','Yakın zamanda cihazın yerinin veya tesisatın değişip değişmediği'],safeHeading:'Sızıntı riskinden kaçının',safeChecks:['Su vanasının konumunu ve evde su olup olmadığını dışarıdan kontrol edin.','Hortumu çekmeyin veya bağlantı sökmeyin; kodu fotoğraflayın.'],serviceTrigger:'Su kaçağı, elektrikle temas riski veya hortum hasarı varsa cihazı kullanmayın; bağlantıya müdahale etmeden servisle görüşün.',tellService:'Model, hata kodu, program ve su kesintisi/tesisat değişikliği bilgisini paylaşın.',serviceSlugs:['camasir-makinesi-servisi'],related:['camasir-makinesi-sikmiyor','servis-cagirirken-hangi-bilgiler']},
 'bulasik-makinesi-su-birakiyor':{category:'Beyaz eşya arızaları',answer:'Program sonunda tabanda su kalması tahliye koşulları, filtre bölgesi veya pompa hattıyla ilişkili olabilir. Makine içindeki az miktarda su bazı modellerde tasarım gereği görülebilir.',diagnosticHeading:'Kalan suyun miktarını gözlemleyin',observations:['Suyun filtre çevresinde mi, tabanda mı kaldığı','Program sonunda tahliye sesi duyulup duyulmadığı','Ekranda hata kodu veya su kaçağı olup olmadığı'],safeHeading:'Filtreyi sökmeden önce kılavuza bakın',safeChecks:['Programı bitirin ve cihazın sıcak parçalarının soğumasını bekleyin.','Erişilebilir filtre için yalnızca model kılavuzundaki kullanıcı temizliği adımını izleyin.'],serviceTrigger:'Pompa veya tahliye hattını sökmeyin; su elektrikli bölüme ulaşıyorsa cihaza dokunmayın.',tellService:'Kalan suyun görünümü, program, kod ve tahliye sesi bilgisini verin.',serviceSlugs:['bulasik-makinesi-servisi','beyaz-esya-tamiri'],related:['bulasik-makinesi-iyi-yikamiyor','servis-cagirirken-hangi-bilgiler']},
 'bulasik-makinesi-iyi-yikamiyor':{category:'Beyaz eşya arızaları',answer:'Yıkama sonucu; yükleme, program, deterjan ve su püskürtme koşullarından etkilenebilir. Sorun sürüyorsa cihazın su alma/ısıtma/tahliye işlevleri de değerlendirilmelidir.',diagnosticHeading:'Son yıkama döngüsünü gözden geçirin',observations:['Seçilen program ve yükleme yoğunluğu','Püskürtme kollarının bulaşıkla engellenip engellenmediği','Deterjan türü, uyarı kodu veya su kalıntısı'],safeHeading:'Kılavuzdaki kullanıcı bakımını uygulayın',safeChecks:['Bulaşıkların püskürtme kolunu engellemediğini gözle kontrol edin.','Filtre temizliğini ve deterjan kullanımını model talimatına göre değerlendirin.'],serviceTrigger:'Isıtıcı, pompa, elektrik bağlantısı veya su hattını sökmeyin. Koku, kaçak veya tekrarlayan hata varsa servis isteyin.',tellService:'Program, yükleme biçimi, kullanılan deterjan ve gözlenen kalıntıyı tarif edin.',serviceSlugs:['bulasik-makinesi-servisi'],related:['bulasik-makinesi-su-birakiyor','beyaz-esya-bakim-rehberi']},
 'kurutma-makinesi-kurutmuyor':{category:'Beyaz eşya arızaları',answer:'Kurutma süresi ve sonuç; yük miktarı, seçili program ve hava akışını etkileyen filtre bakımına bağlıdır. İç kanallar veya ısıtıcı sistem kullanıcı müdahalesi için değildir.',diagnosticHeading:'Program ve yük koşulunu inceleyin',observations:['Programın kumaş türüne uygun olup olmadığı','Yükün makinenin kapasitesine göre durumu','Filtre veya su haznesi uyarısının yanıp yanmadığı'],safeHeading:'Kullanım kılavuzundaki rutin adımlar',safeChecks:['Tüy filtresini ve su haznesini model kılavuzuna göre kontrol edin.','Yükü ve programı cihazın kapasite talimatlarıyla karşılaştırın.'],serviceTrigger:'Yanık kokusu, aşırı ısınma veya tekrarlayan uyarı varsa cihazı kapatın. Isıtıcı ve iç hava kanallarını sökmeyin.',tellService:'Model, program, yük miktarı, filtre/hazne uyarısı ve süre değişimini paylaşın.',serviceSlugs:['kurutma-makinesi-servisi','beyaz-esya-tamiri'],related:['beyaz-esya-bakim-rehberi','servis-cagirirken-hangi-bilgiler']},
 'beyaz-esya-voltaj-koruma':{category:'Güvenli kullanım',answer:'Elektrik dalgalanması ve kesinti cihazları etkileyebilir; hasarı önlemenin yolu cihazın üretici yönergesine ve elektrik tesisatı güvenliğine uymaktır.',diagnosticHeading:'Elektrik olayı sonrası belirtileri kaydedin',observations:['Kesinti veya dalgalanma zamanı','Cihazda görünen kod ya da panel ışıkları','Sigorta atması, yanık kokusu veya kablo ısınması'],safeHeading:'Elektrik güvenliğini önceleyin',safeChecks:['Priz, fiş veya kabloda hasar görürseniz cihaza dokunmayın.','Uzatma/priz kullanımı ve koruma ekipmanı için cihaz kılavuzu ile ehil elektrik uzmanının önerisini izleyin.'],serviceTrigger:'Sigorta tekrar atıyorsa, kıvılcım veya yanık kokusu varsa cihazı çalıştırmayı denemeyin; güvenliyse enerjiyi kesin ve teknik destek alın.',tellService:'Olayın saati, etkilenen cihazlar, panel kodu ve evdeki elektrik belirtisini paylaşın.',serviceSlugs:['beyaz-esya-tamiri','klima-tamiri'],related:['buzdolabi-sogutmuyor','servis-cagirirken-hangi-bilgiler']},
 'servis-cagirirken-hangi-bilgiler':{metaTitle:'Teknik Servis Kaydı İçin Hazırlık | Dost Teknik',category:'Servis hazırlığı',answer:'Doğru ilk değerlendirme için cihaz türü, model etiketi, belirti, varsa hata kodu ve bulunduğunuz bölgeyi hazırlayın.',diagnosticHeading:'Kısa servis notu oluşturun',observations:['Cihazın türü ve marka-modeli','Belirtinin ne zaman başladığı ve hangi kullanımda oluştuğu','Görünen kod, sızıntı veya çalışma sesi'],safeHeading:'Paylaşmadan önce güvenli kayıt',safeChecks:['Model etiketini cihazı sökmeden, erişilebilir konumdaysa fotoğraflayın.','Hata kodu ve sesi uzaktan kaydedin; elektrikli bölümleri açmayın.'],serviceTrigger:'Cihaz güvenli değilse sorun gidermeyi sürdürmeyin; telefonla önce durumu ve bölgeyi aktarın.',tellService:'Telefon veya WhatsApp mesajında cihaz, model, belirti, kod ve konum bilgisini kısa maddelerle yazın.',serviceSlugs:['klima-tamiri','beyaz-esya-tamiri'],related:['klima-neden-sogutmaz','buzdolabi-sogutmuyor','camasir-makinesi-sikmiyor']},
 'klima-filtre-temizligi':{category:'Klima bakımı',answer:'Kullanıcı filtresinin temizlik aralığı ve yöntemi klima modeline göre değişir; üretici kılavuzunu izlemek en güvenli yoldur.',diagnosticHeading:'Filtre bakımını hangi koşulda düşünmeli?',observations:['Kılavuzdaki bakım uyarısı veya periyot','Hava akışında fark edilir azalma','Filtre yüzeyinde görülebilir toz birikimi'],safeHeading:'Model talimatı dışına çıkmayın',safeChecks:['Temizlik öncesinde cihazı kılavuzun tarif ettiği şekilde kapatın.','Filtreyi yumuşak biçimde temizleyip tamamen kurutmadan geri takmayın.'],serviceTrigger:'Filtreye erişmek için gövdeyi açmanız gerekiyorsa veya koku/performans sorunu sürüyorsa iç ünite temizliğini servise bırakın.',tellService:'Modeli, filtre uyarısını ve son temizlik zamanını bildirin.',serviceSlugs:['klima-bakimi','klima-temizligi'],related:['klima-bakimi-ne-zaman-yapilmali','klima-koku-yapiyor']},
 'klima-enerji-verimliligi':{category:'Klima kullanımı',answer:'Verimli kullanım için doğru kapasite ve ayar, filtre bakımı, gölgelenme ve kapı/pencere koşulları birlikte değerlendirilir. Sonuç ortam ve cihaz özelliklerine bağlıdır.',diagnosticHeading:'Günlük kullanımda etkili koşullar',observations:['Kapı/pencere ve güneş alan yüzeylerin durumu','Seçilen mod ve hedef sıcaklık','Filtre uyarısı, hava akışı ve odadaki ısı yükü'],safeHeading:'Ayarlarda küçük ve güvenli adımlar',safeChecks:['Kullanım kılavuzundaki çalışma modlarını ve ayar açıklamalarını izleyin.','Kapı ve pencereleri kapalı tutup doğrudan güneş alan perde/panjurları değerlendirin.'],serviceTrigger:'Ayarlar uygun olsa da performans belirgin düştüyse teknik arıza ihtimali için servis kontrolü isteyin; soğutucu devreye dokunmayın.',tellService:'Oda koşullarını, kullanım saatini, seçilen ayarı ve performans değişimini paylaşın.',serviceSlugs:['klima-bakimi','klima-tamiri'],related:['klima-bakimi-ne-zaman-yapilmali','klima-filtre-temizligi','bodrum-nem-klima-bakimi']},
 'beyaz-esya-bakim-rehberi':{category:'Beyaz eşya bakımı',answer:'Düzenli kullanıcı bakımı cihaz türüne ve model kılavuzuna göre değişir. Filtre ve erişilebilir yüzeylerin bakımı ile teknik iç bakım birbirinden ayrılmalıdır.',diagnosticHeading:'Her cihaz için kılavuzdaki rutinleri bulun',observations:['Cihazda bakım/filtre uyarısı','Program veya performans değişikliği','Son kullanıcı bakımının ne zaman yapıldığı'],safeHeading:'Yalnızca kullanıcıya açık noktalar',safeChecks:['Filtre, hazne veya erişilebilir yüzeyleri ürün kılavuzuna göre temizleyin.','Cihazın elektrik bağlantısı ve su/gaz hatlarına müdahale etmeyin.'],serviceTrigger:'İç parçaların sökülmesi, elektrik ölçümü ve pompa/ısıtma sistemi bakımı servis işlemidir.',tellService:'Cihaz türü, model, bakım uyarısı ve gözlenen belirtiyi paylaşın.',serviceSlugs:['beyaz-esya-tamiri','klima-bakimi'],related:['servis-cagirirken-hangi-bilgiler','klima-bakimi-ne-zaman-yapilmali','kurutma-makinesi-kurutmuyor']}
};

export const enrichedGuides = guides.map(g=>({...g,...guideDetails[g.slug],relatedGuides:guideDetails[g.slug].related.map(slug=>guides.find(x=>x.slug===slug)).filter(Boolean)}));

// Only 19 region destinations visibly linked from all 60 brand detail pages.
export const linkedRegionSlugs = ['akcaalan','bahcelievler','karabag','islamhaneleri','akyarlar','karaincir','bagla','gumusluk','gumuskaya','koyunbaba','ortakent','yahsi','bitez','gumbet','konacik','bodrum-merkez','torba','yalikavak','gundogan'];
export const brandPagePairs = brands.flatMap(brand => linkedRegionSlugs.map(regionSlug => ({brand,region:regions.find(r=>r.slug===regionSlug),verifiedFrom:'brand'})));
export const regionPagePairs = brands.slice(0,36).map(brand => ({brand,region:regions.find(r=>r.slug==='cevat-sakir'),verifiedFrom:'region'}));
export const brandRegionPairs = [...brandPagePairs,...regionPagePairs];

export const knownUrls = [
 '/', '/hizmetler/','/bolgeler/','/markalar/','/bilgi-merkezi/',
 ...services.map(x=>x.url), ...regions.map(x=>x.url), ...brands.map(x=>x.url), ...guides.map(x=>x.url),
 '/hakkimizda.html','/iletisim.html',
 ...brandRegionPairs.map(x=>`/servis/${x.region.slug}/${x.brand.slug}-servisi.html`)
];
